//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LabManagerCliente.CopiasDeSeguridadService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DtoBase", Namespace="http://schemas.datacontract.org/2004/07/Dtos")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(LabManagerCliente.CopiasDeSeguridadService.InformacionCopiasDeSeguridad))]
    public partial class DtoBase : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool ErrorField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MensajeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private byte[] TokenField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Error {
            get {
                return this.ErrorField;
            }
            set {
                if ((this.ErrorField.Equals(value) != true)) {
                    this.ErrorField = value;
                    this.RaisePropertyChanged("Error");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Mensaje {
            get {
                return this.MensajeField;
            }
            set {
                if ((object.ReferenceEquals(this.MensajeField, value) != true)) {
                    this.MensajeField = value;
                    this.RaisePropertyChanged("Mensaje");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public byte[] Token {
            get {
                return this.TokenField;
            }
            set {
                if ((object.ReferenceEquals(this.TokenField, value) != true)) {
                    this.TokenField = value;
                    this.RaisePropertyChanged("Token");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="InformacionCopiasDeSeguridad", Namespace="http://schemas.datacontract.org/2004/07/Dtos.Gestion")]
    [System.SerializableAttribute()]
    public partial class InformacionCopiasDeSeguridad : LabManagerCliente.CopiasDeSeguridadService.DtoBase {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string[] ArchivosField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool DefaultField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PathField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string[] Archivos {
            get {
                return this.ArchivosField;
            }
            set {
                if ((object.ReferenceEquals(this.ArchivosField, value) != true)) {
                    this.ArchivosField = value;
                    this.RaisePropertyChanged("Archivos");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Default {
            get {
                return this.DefaultField;
            }
            set {
                if ((this.DefaultField.Equals(value) != true)) {
                    this.DefaultField = value;
                    this.RaisePropertyChanged("Default");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Path {
            get {
                return this.PathField;
            }
            set {
                if ((object.ReferenceEquals(this.PathField, value) != true)) {
                    this.PathField = value;
                    this.RaisePropertyChanged("Path");
                }
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="CopiasDeSeguridadService.ICopiasDeSeguridad")]
    public interface ICopiasDeSeguridad {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICopiasDeSeguridad/getInformacionBackup", ReplyAction="http://tempuri.org/ICopiasDeSeguridad/getInformacionBackupResponse")]
        LabManagerCliente.CopiasDeSeguridadService.InformacionCopiasDeSeguridad getInformacionBackup(long UsuarioId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICopiasDeSeguridad/getInformacionBackup", ReplyAction="http://tempuri.org/ICopiasDeSeguridad/getInformacionBackupResponse")]
        System.Threading.Tasks.Task<LabManagerCliente.CopiasDeSeguridadService.InformacionCopiasDeSeguridad> getInformacionBackupAsync(long UsuarioId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICopiasDeSeguridad/CreateBackup", ReplyAction="http://tempuri.org/ICopiasDeSeguridad/CreateBackupResponse")]
        LabManagerCliente.CopiasDeSeguridadService.DtoBase CreateBackup();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICopiasDeSeguridad/CreateBackup", ReplyAction="http://tempuri.org/ICopiasDeSeguridad/CreateBackupResponse")]
        System.Threading.Tasks.Task<LabManagerCliente.CopiasDeSeguridadService.DtoBase> CreateBackupAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICopiasDeSeguridad/RestoreBackup", ReplyAction="http://tempuri.org/ICopiasDeSeguridad/RestoreBackupResponse")]
        LabManagerCliente.CopiasDeSeguridadService.DtoBase RestoreBackup(string file, long UserId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICopiasDeSeguridad/RestoreBackup", ReplyAction="http://tempuri.org/ICopiasDeSeguridad/RestoreBackupResponse")]
        System.Threading.Tasks.Task<LabManagerCliente.CopiasDeSeguridadService.DtoBase> RestoreBackupAsync(string file, long UserId);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ICopiasDeSeguridadChannel : LabManagerCliente.CopiasDeSeguridadService.ICopiasDeSeguridad, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class CopiasDeSeguridadClient : System.ServiceModel.ClientBase<LabManagerCliente.CopiasDeSeguridadService.ICopiasDeSeguridad>, LabManagerCliente.CopiasDeSeguridadService.ICopiasDeSeguridad {
        
        public CopiasDeSeguridadClient() {
        }
        
        public CopiasDeSeguridadClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public CopiasDeSeguridadClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CopiasDeSeguridadClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CopiasDeSeguridadClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public LabManagerCliente.CopiasDeSeguridadService.InformacionCopiasDeSeguridad getInformacionBackup(long UsuarioId) {
            return base.Channel.getInformacionBackup(UsuarioId);
        }
        
        public System.Threading.Tasks.Task<LabManagerCliente.CopiasDeSeguridadService.InformacionCopiasDeSeguridad> getInformacionBackupAsync(long UsuarioId) {
            return base.Channel.getInformacionBackupAsync(UsuarioId);
        }
        
        public LabManagerCliente.CopiasDeSeguridadService.DtoBase CreateBackup() {
            return base.Channel.CreateBackup();
        }
        
        public System.Threading.Tasks.Task<LabManagerCliente.CopiasDeSeguridadService.DtoBase> CreateBackupAsync() {
            return base.Channel.CreateBackupAsync();
        }
        
        public LabManagerCliente.CopiasDeSeguridadService.DtoBase RestoreBackup(string file, long UserId) {
            return base.Channel.RestoreBackup(file, UserId);
        }
        
        public System.Threading.Tasks.Task<LabManagerCliente.CopiasDeSeguridadService.DtoBase> RestoreBackupAsync(string file, long UserId) {
            return base.Channel.RestoreBackupAsync(file, UserId);
        }
    }
}
