//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LabManagerCliente.InactivarEstudianteService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DtoBase", Namespace="http://schemas.datacontract.org/2004/07/Dtos")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(LabManagerCliente.InactivarEstudianteService.Parametro))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(LabManagerCliente.InactivarEstudianteService.InformacionInactivar))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(LabManagerCliente.InactivarEstudianteService.DtoBool))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(LabManagerCliente.InactivarEstudianteService.Lista_View_Parametros))]
    public partial class DtoBase : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool ErrorField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MensajeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private byte[] TokenField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Error {
            get {
                return this.ErrorField;
            }
            set {
                if ((this.ErrorField.Equals(value) != true)) {
                    this.ErrorField = value;
                    this.RaisePropertyChanged("Error");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Mensaje {
            get {
                return this.MensajeField;
            }
            set {
                if ((object.ReferenceEquals(this.MensajeField, value) != true)) {
                    this.MensajeField = value;
                    this.RaisePropertyChanged("Mensaje");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public byte[] Token {
            get {
                return this.TokenField;
            }
            set {
                if ((object.ReferenceEquals(this.TokenField, value) != true)) {
                    this.TokenField = value;
                    this.RaisePropertyChanged("Token");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Parametro", Namespace="http://schemas.datacontract.org/2004/07/Dtos.Gestion")]
    [System.SerializableAttribute()]
    public partial class Parametro : LabManagerCliente.InactivarEstudianteService.DtoBase {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescripcionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NombreField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ParametroIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ValorField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Descripcion {
            get {
                return this.DescripcionField;
            }
            set {
                if ((object.ReferenceEquals(this.DescripcionField, value) != true)) {
                    this.DescripcionField = value;
                    this.RaisePropertyChanged("Descripcion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Nombre {
            get {
                return this.NombreField;
            }
            set {
                if ((object.ReferenceEquals(this.NombreField, value) != true)) {
                    this.NombreField = value;
                    this.RaisePropertyChanged("Nombre");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ParametroId {
            get {
                return this.ParametroIdField;
            }
            set {
                if ((this.ParametroIdField.Equals(value) != true)) {
                    this.ParametroIdField = value;
                    this.RaisePropertyChanged("ParametroId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Valor {
            get {
                return this.ValorField;
            }
            set {
                if ((object.ReferenceEquals(this.ValorField, value) != true)) {
                    this.ValorField = value;
                    this.RaisePropertyChanged("Valor");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="InformacionInactivar", Namespace="http://schemas.datacontract.org/2004/07/Dtos.Gestion")]
    [System.SerializableAttribute()]
    public partial class InformacionInactivar : LabManagerCliente.InactivarEstudianteService.DtoBase {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int EstudiantesActivosField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int EstudiantesInactivosField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int EstudiantesTotalField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int EstudiantesActivos {
            get {
                return this.EstudiantesActivosField;
            }
            set {
                if ((this.EstudiantesActivosField.Equals(value) != true)) {
                    this.EstudiantesActivosField = value;
                    this.RaisePropertyChanged("EstudiantesActivos");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int EstudiantesInactivos {
            get {
                return this.EstudiantesInactivosField;
            }
            set {
                if ((this.EstudiantesInactivosField.Equals(value) != true)) {
                    this.EstudiantesInactivosField = value;
                    this.RaisePropertyChanged("EstudiantesInactivos");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int EstudiantesTotal {
            get {
                return this.EstudiantesTotalField;
            }
            set {
                if ((this.EstudiantesTotalField.Equals(value) != true)) {
                    this.EstudiantesTotalField = value;
                    this.RaisePropertyChanged("EstudiantesTotal");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DtoBool", Namespace="http://schemas.datacontract.org/2004/07/Dtos")]
    [System.SerializableAttribute()]
    public partial class DtoBool : LabManagerCliente.InactivarEstudianteService.DtoBase {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool ValorField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Valor {
            get {
                return this.ValorField;
            }
            set {
                if ((this.ValorField.Equals(value) != true)) {
                    this.ValorField = value;
                    this.RaisePropertyChanged("Valor");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Lista_View_Parametros", Namespace="http://schemas.datacontract.org/2004/07/Dtos.Gestion")]
    [System.SerializableAttribute()]
    public partial class Lista_View_Parametros : LabManagerCliente.InactivarEstudianteService.DtoBase {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private LabManagerCliente.InactivarEstudianteService.Parametro[] ItemsField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public LabManagerCliente.InactivarEstudianteService.Parametro[] Items {
            get {
                return this.ItemsField;
            }
            set {
                if ((object.ReferenceEquals(this.ItemsField, value) != true)) {
                    this.ItemsField = value;
                    this.RaisePropertyChanged("Items");
                }
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="InactivarEstudianteService.IInactivarEstudiante")]
    public interface IInactivarEstudiante {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IInactivarEstudiante/getParametros", ReplyAction="http://tempuri.org/IInactivarEstudiante/getParametrosResponse")]
        LabManagerCliente.InactivarEstudianteService.Lista_View_Parametros getParametros(string FiltroTexto, int UsuarioId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IInactivarEstudiante/getParametros", ReplyAction="http://tempuri.org/IInactivarEstudiante/getParametrosResponse")]
        System.Threading.Tasks.Task<LabManagerCliente.InactivarEstudianteService.Lista_View_Parametros> getParametrosAsync(string FiltroTexto, int UsuarioId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IInactivarEstudiante/getInformacionInactivar", ReplyAction="http://tempuri.org/IInactivarEstudiante/getInformacionInactivarResponse")]
        LabManagerCliente.InactivarEstudianteService.InformacionInactivar getInformacionInactivar();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IInactivarEstudiante/getInformacionInactivar", ReplyAction="http://tempuri.org/IInactivarEstudiante/getInformacionInactivarResponse")]
        System.Threading.Tasks.Task<LabManagerCliente.InactivarEstudianteService.InformacionInactivar> getInformacionInactivarAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IInactivarEstudiante/InactivarEstudiantes", ReplyAction="http://tempuri.org/IInactivarEstudiante/InactivarEstudiantesResponse")]
        LabManagerCliente.InactivarEstudianteService.DtoBase InactivarEstudiantes(long UsuarioId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IInactivarEstudiante/InactivarEstudiantes", ReplyAction="http://tempuri.org/IInactivarEstudiante/InactivarEstudiantesResponse")]
        System.Threading.Tasks.Task<LabManagerCliente.InactivarEstudianteService.DtoBase> InactivarEstudiantesAsync(long UsuarioId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IInactivarEstudiante/ActivarEstudiantes", ReplyAction="http://tempuri.org/IInactivarEstudiante/ActivarEstudiantesResponse")]
        LabManagerCliente.InactivarEstudianteService.DtoBase ActivarEstudiantes(long UsuarioId, long UsuarioIdActivar);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IInactivarEstudiante/ActivarEstudiantes", ReplyAction="http://tempuri.org/IInactivarEstudiante/ActivarEstudiantesResponse")]
        System.Threading.Tasks.Task<LabManagerCliente.InactivarEstudianteService.DtoBase> ActivarEstudiantesAsync(long UsuarioId, long UsuarioIdActivar);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IInactivarEstudiante/IsUserActive", ReplyAction="http://tempuri.org/IInactivarEstudiante/IsUserActiveResponse")]
        LabManagerCliente.InactivarEstudianteService.DtoBool IsUserActive(string BarCode);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IInactivarEstudiante/IsUserActive", ReplyAction="http://tempuri.org/IInactivarEstudiante/IsUserActiveResponse")]
        System.Threading.Tasks.Task<LabManagerCliente.InactivarEstudianteService.DtoBool> IsUserActiveAsync(string BarCode);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IInactivarEstudianteChannel : LabManagerCliente.InactivarEstudianteService.IInactivarEstudiante, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class InactivarEstudianteClient : System.ServiceModel.ClientBase<LabManagerCliente.InactivarEstudianteService.IInactivarEstudiante>, LabManagerCliente.InactivarEstudianteService.IInactivarEstudiante {
        
        public InactivarEstudianteClient() {
        }
        
        public InactivarEstudianteClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public InactivarEstudianteClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public InactivarEstudianteClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public InactivarEstudianteClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public LabManagerCliente.InactivarEstudianteService.Lista_View_Parametros getParametros(string FiltroTexto, int UsuarioId) {
            return base.Channel.getParametros(FiltroTexto, UsuarioId);
        }
        
        public System.Threading.Tasks.Task<LabManagerCliente.InactivarEstudianteService.Lista_View_Parametros> getParametrosAsync(string FiltroTexto, int UsuarioId) {
            return base.Channel.getParametrosAsync(FiltroTexto, UsuarioId);
        }
        
        public LabManagerCliente.InactivarEstudianteService.InformacionInactivar getInformacionInactivar() {
            return base.Channel.getInformacionInactivar();
        }
        
        public System.Threading.Tasks.Task<LabManagerCliente.InactivarEstudianteService.InformacionInactivar> getInformacionInactivarAsync() {
            return base.Channel.getInformacionInactivarAsync();
        }
        
        public LabManagerCliente.InactivarEstudianteService.DtoBase InactivarEstudiantes(long UsuarioId) {
            return base.Channel.InactivarEstudiantes(UsuarioId);
        }
        
        public System.Threading.Tasks.Task<LabManagerCliente.InactivarEstudianteService.DtoBase> InactivarEstudiantesAsync(long UsuarioId) {
            return base.Channel.InactivarEstudiantesAsync(UsuarioId);
        }
        
        public LabManagerCliente.InactivarEstudianteService.DtoBase ActivarEstudiantes(long UsuarioId, long UsuarioIdActivar) {
            return base.Channel.ActivarEstudiantes(UsuarioId, UsuarioIdActivar);
        }
        
        public System.Threading.Tasks.Task<LabManagerCliente.InactivarEstudianteService.DtoBase> ActivarEstudiantesAsync(long UsuarioId, long UsuarioIdActivar) {
            return base.Channel.ActivarEstudiantesAsync(UsuarioId, UsuarioIdActivar);
        }
        
        public LabManagerCliente.InactivarEstudianteService.DtoBool IsUserActive(string BarCode) {
            return base.Channel.IsUserActive(BarCode);
        }
        
        public System.Threading.Tasks.Task<LabManagerCliente.InactivarEstudianteService.DtoBool> IsUserActiveAsync(string BarCode) {
            return base.Channel.IsUserActiveAsync(BarCode);
        }
    }
}
