//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LabManagerCliente.PrestamoRecepcionService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DtoBase", Namespace="http://schemas.datacontract.org/2004/07/Dtos")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(LabManagerCliente.PrestamoRecepcionService.DtoInt))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(LabManagerCliente.PrestamoRecepcionService.Restriccion))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(LabManagerCliente.PrestamoRecepcionService.View_AnotacionesActivas))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(LabManagerCliente.PrestamoRecepcionService.View_EquiposACargo))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(LabManagerCliente.PrestamoRecepcionService.View_MultasActivas))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(LabManagerCliente.PrestamoRecepcionService.RestriccionDto))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(LabManagerCliente.PrestamoRecepcionService.View_PrestamoRecepcion))]
    public partial class DtoBase : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool ErrorField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MensajeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private byte[] TokenField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Error {
            get {
                return this.ErrorField;
            }
            set {
                if ((this.ErrorField.Equals(value) != true)) {
                    this.ErrorField = value;
                    this.RaisePropertyChanged("Error");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Mensaje {
            get {
                return this.MensajeField;
            }
            set {
                if ((object.ReferenceEquals(this.MensajeField, value) != true)) {
                    this.MensajeField = value;
                    this.RaisePropertyChanged("Mensaje");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public byte[] Token {
            get {
                return this.TokenField;
            }
            set {
                if ((object.ReferenceEquals(this.TokenField, value) != true)) {
                    this.TokenField = value;
                    this.RaisePropertyChanged("Token");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DtoInt", Namespace="http://schemas.datacontract.org/2004/07/Dtos")]
    [System.SerializableAttribute()]
    public partial class DtoInt : LabManagerCliente.PrestamoRecepcionService.DtoBase {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long ValorField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long Valor {
            get {
                return this.ValorField;
            }
            set {
                if ((this.ValorField.Equals(value) != true)) {
                    this.ValorField = value;
                    this.RaisePropertyChanged("Valor");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Restriccion", Namespace="http://schemas.datacontract.org/2004/07/Dtos.Basico")]
    [System.SerializableAttribute()]
    public partial class Restriccion : LabManagerCliente.PrestamoRecepcionService.DtoBase {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool ActivoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long CreadoIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescripcionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime FechaCreacionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> FechaModificacionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<long> ModificadoIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int RestriccionIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TextoField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Activo {
            get {
                return this.ActivoField;
            }
            set {
                if ((this.ActivoField.Equals(value) != true)) {
                    this.ActivoField = value;
                    this.RaisePropertyChanged("Activo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long CreadoId {
            get {
                return this.CreadoIdField;
            }
            set {
                if ((this.CreadoIdField.Equals(value) != true)) {
                    this.CreadoIdField = value;
                    this.RaisePropertyChanged("CreadoId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Descripcion {
            get {
                return this.DescripcionField;
            }
            set {
                if ((object.ReferenceEquals(this.DescripcionField, value) != true)) {
                    this.DescripcionField = value;
                    this.RaisePropertyChanged("Descripcion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime FechaCreacion {
            get {
                return this.FechaCreacionField;
            }
            set {
                if ((this.FechaCreacionField.Equals(value) != true)) {
                    this.FechaCreacionField = value;
                    this.RaisePropertyChanged("FechaCreacion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> FechaModificacion {
            get {
                return this.FechaModificacionField;
            }
            set {
                if ((this.FechaModificacionField.Equals(value) != true)) {
                    this.FechaModificacionField = value;
                    this.RaisePropertyChanged("FechaModificacion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<long> ModificadoId {
            get {
                return this.ModificadoIdField;
            }
            set {
                if ((this.ModificadoIdField.Equals(value) != true)) {
                    this.ModificadoIdField = value;
                    this.RaisePropertyChanged("ModificadoId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int RestriccionId {
            get {
                return this.RestriccionIdField;
            }
            set {
                if ((this.RestriccionIdField.Equals(value) != true)) {
                    this.RestriccionIdField = value;
                    this.RaisePropertyChanged("RestriccionId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Texto {
            get {
                return this.TextoField;
            }
            set {
                if ((object.ReferenceEquals(this.TextoField, value) != true)) {
                    this.TextoField = value;
                    this.RaisePropertyChanged("Texto");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="View_AnotacionesActivas", Namespace="http://schemas.datacontract.org/2004/07/Dtos.Registro")]
    [System.SerializableAttribute()]
    public partial class View_AnotacionesActivas : LabManagerCliente.PrestamoRecepcionService.DtoBase {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long AnotacionIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescripcionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DocumentoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime FechaCreacionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NombreField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NombreCreadorField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NombreModificaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<long> UsuarioIdField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long AnotacionId {
            get {
                return this.AnotacionIdField;
            }
            set {
                if ((this.AnotacionIdField.Equals(value) != true)) {
                    this.AnotacionIdField = value;
                    this.RaisePropertyChanged("AnotacionId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Descripcion {
            get {
                return this.DescripcionField;
            }
            set {
                if ((object.ReferenceEquals(this.DescripcionField, value) != true)) {
                    this.DescripcionField = value;
                    this.RaisePropertyChanged("Descripcion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Documento {
            get {
                return this.DocumentoField;
            }
            set {
                if ((object.ReferenceEquals(this.DocumentoField, value) != true)) {
                    this.DocumentoField = value;
                    this.RaisePropertyChanged("Documento");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime FechaCreacion {
            get {
                return this.FechaCreacionField;
            }
            set {
                if ((this.FechaCreacionField.Equals(value) != true)) {
                    this.FechaCreacionField = value;
                    this.RaisePropertyChanged("FechaCreacion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Nombre {
            get {
                return this.NombreField;
            }
            set {
                if ((object.ReferenceEquals(this.NombreField, value) != true)) {
                    this.NombreField = value;
                    this.RaisePropertyChanged("Nombre");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NombreCreador {
            get {
                return this.NombreCreadorField;
            }
            set {
                if ((object.ReferenceEquals(this.NombreCreadorField, value) != true)) {
                    this.NombreCreadorField = value;
                    this.RaisePropertyChanged("NombreCreador");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NombreModifica {
            get {
                return this.NombreModificaField;
            }
            set {
                if ((object.ReferenceEquals(this.NombreModificaField, value) != true)) {
                    this.NombreModificaField = value;
                    this.RaisePropertyChanged("NombreModifica");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<long> UsuarioId {
            get {
                return this.UsuarioIdField;
            }
            set {
                if ((this.UsuarioIdField.Equals(value) != true)) {
                    this.UsuarioIdField = value;
                    this.RaisePropertyChanged("UsuarioId");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="View_EquiposACargo", Namespace="http://schemas.datacontract.org/2004/07/Dtos.Registro")]
    [System.SerializableAttribute()]
    public partial class View_EquiposACargo : LabManagerCliente.PrestamoRecepcionService.DtoBase {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CodigoLaboratorioField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long EquipoIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool PrestadoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TipoEquipoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long UsuarioIdField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CodigoLaboratorio {
            get {
                return this.CodigoLaboratorioField;
            }
            set {
                if ((object.ReferenceEquals(this.CodigoLaboratorioField, value) != true)) {
                    this.CodigoLaboratorioField = value;
                    this.RaisePropertyChanged("CodigoLaboratorio");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long EquipoId {
            get {
                return this.EquipoIdField;
            }
            set {
                if ((this.EquipoIdField.Equals(value) != true)) {
                    this.EquipoIdField = value;
                    this.RaisePropertyChanged("EquipoId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Prestado {
            get {
                return this.PrestadoField;
            }
            set {
                if ((this.PrestadoField.Equals(value) != true)) {
                    this.PrestadoField = value;
                    this.RaisePropertyChanged("Prestado");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TipoEquipo {
            get {
                return this.TipoEquipoField;
            }
            set {
                if ((object.ReferenceEquals(this.TipoEquipoField, value) != true)) {
                    this.TipoEquipoField = value;
                    this.RaisePropertyChanged("TipoEquipo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long UsuarioId {
            get {
                return this.UsuarioIdField;
            }
            set {
                if ((this.UsuarioIdField.Equals(value) != true)) {
                    this.UsuarioIdField = value;
                    this.RaisePropertyChanged("UsuarioId");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="View_MultasActivas", Namespace="http://schemas.datacontract.org/2004/07/Dtos.Registro")]
    [System.SerializableAttribute()]
    public partial class View_MultasActivas : LabManagerCliente.PrestamoRecepcionService.DtoBase {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescripcionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long DeudorIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DocumentoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime FechaCreacionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> FechaModificacionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long MultaIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NombreField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NombreCreadorField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NombreModificaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ValorField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Descripcion {
            get {
                return this.DescripcionField;
            }
            set {
                if ((object.ReferenceEquals(this.DescripcionField, value) != true)) {
                    this.DescripcionField = value;
                    this.RaisePropertyChanged("Descripcion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long DeudorId {
            get {
                return this.DeudorIdField;
            }
            set {
                if ((this.DeudorIdField.Equals(value) != true)) {
                    this.DeudorIdField = value;
                    this.RaisePropertyChanged("DeudorId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Documento {
            get {
                return this.DocumentoField;
            }
            set {
                if ((object.ReferenceEquals(this.DocumentoField, value) != true)) {
                    this.DocumentoField = value;
                    this.RaisePropertyChanged("Documento");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime FechaCreacion {
            get {
                return this.FechaCreacionField;
            }
            set {
                if ((this.FechaCreacionField.Equals(value) != true)) {
                    this.FechaCreacionField = value;
                    this.RaisePropertyChanged("FechaCreacion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> FechaModificacion {
            get {
                return this.FechaModificacionField;
            }
            set {
                if ((this.FechaModificacionField.Equals(value) != true)) {
                    this.FechaModificacionField = value;
                    this.RaisePropertyChanged("FechaModificacion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long MultaId {
            get {
                return this.MultaIdField;
            }
            set {
                if ((this.MultaIdField.Equals(value) != true)) {
                    this.MultaIdField = value;
                    this.RaisePropertyChanged("MultaId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Nombre {
            get {
                return this.NombreField;
            }
            set {
                if ((object.ReferenceEquals(this.NombreField, value) != true)) {
                    this.NombreField = value;
                    this.RaisePropertyChanged("Nombre");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NombreCreador {
            get {
                return this.NombreCreadorField;
            }
            set {
                if ((object.ReferenceEquals(this.NombreCreadorField, value) != true)) {
                    this.NombreCreadorField = value;
                    this.RaisePropertyChanged("NombreCreador");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NombreModifica {
            get {
                return this.NombreModificaField;
            }
            set {
                if ((object.ReferenceEquals(this.NombreModificaField, value) != true)) {
                    this.NombreModificaField = value;
                    this.RaisePropertyChanged("NombreModifica");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Valor {
            get {
                return this.ValorField;
            }
            set {
                if ((this.ValorField.Equals(value) != true)) {
                    this.ValorField = value;
                    this.RaisePropertyChanged("Valor");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="RestriccionDto", Namespace="http://schemas.datacontract.org/2004/07/Dtos.Registro")]
    [System.SerializableAttribute()]
    public partial class RestriccionDto : LabManagerCliente.PrestamoRecepcionService.DtoBase {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private LabManagerCliente.PrestamoRecepcionService.Restriccion[] RestriccionesField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public LabManagerCliente.PrestamoRecepcionService.Restriccion[] Restricciones {
            get {
                return this.RestriccionesField;
            }
            set {
                if ((object.ReferenceEquals(this.RestriccionesField, value) != true)) {
                    this.RestriccionesField = value;
                    this.RaisePropertyChanged("Restricciones");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="View_PrestamoRecepcion", Namespace="http://schemas.datacontract.org/2004/07/Dtos.Registro")]
    [System.SerializableAttribute()]
    public partial class View_PrestamoRecepcion : LabManagerCliente.PrestamoRecepcionService.DtoBase {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool ActivoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private LabManagerCliente.PrestamoRecepcionService.View_AnotacionesActivas[] AnotacionesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ApellidosField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string BarCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private LabManagerCliente.PrestamoRecepcionService.View_EquiposACargo[] EquiposField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FacultadField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> FacultadIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private LabManagerCliente.PrestamoRecepcionService.View_MultasActivas[] MultasField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NombresField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> SemestreBasicoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TipoUsuarioField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int TipoUsuarioIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long UsuarioIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> nAnotacionesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> nEquiposField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> nMultasField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Activo {
            get {
                return this.ActivoField;
            }
            set {
                if ((this.ActivoField.Equals(value) != true)) {
                    this.ActivoField = value;
                    this.RaisePropertyChanged("Activo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public LabManagerCliente.PrestamoRecepcionService.View_AnotacionesActivas[] Anotaciones {
            get {
                return this.AnotacionesField;
            }
            set {
                if ((object.ReferenceEquals(this.AnotacionesField, value) != true)) {
                    this.AnotacionesField = value;
                    this.RaisePropertyChanged("Anotaciones");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Apellidos {
            get {
                return this.ApellidosField;
            }
            set {
                if ((object.ReferenceEquals(this.ApellidosField, value) != true)) {
                    this.ApellidosField = value;
                    this.RaisePropertyChanged("Apellidos");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string BarCode {
            get {
                return this.BarCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.BarCodeField, value) != true)) {
                    this.BarCodeField = value;
                    this.RaisePropertyChanged("BarCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public LabManagerCliente.PrestamoRecepcionService.View_EquiposACargo[] Equipos {
            get {
                return this.EquiposField;
            }
            set {
                if ((object.ReferenceEquals(this.EquiposField, value) != true)) {
                    this.EquiposField = value;
                    this.RaisePropertyChanged("Equipos");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Facultad {
            get {
                return this.FacultadField;
            }
            set {
                if ((object.ReferenceEquals(this.FacultadField, value) != true)) {
                    this.FacultadField = value;
                    this.RaisePropertyChanged("Facultad");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> FacultadId {
            get {
                return this.FacultadIdField;
            }
            set {
                if ((this.FacultadIdField.Equals(value) != true)) {
                    this.FacultadIdField = value;
                    this.RaisePropertyChanged("FacultadId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public LabManagerCliente.PrestamoRecepcionService.View_MultasActivas[] Multas {
            get {
                return this.MultasField;
            }
            set {
                if ((object.ReferenceEquals(this.MultasField, value) != true)) {
                    this.MultasField = value;
                    this.RaisePropertyChanged("Multas");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Nombres {
            get {
                return this.NombresField;
            }
            set {
                if ((object.ReferenceEquals(this.NombresField, value) != true)) {
                    this.NombresField = value;
                    this.RaisePropertyChanged("Nombres");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> SemestreBasico {
            get {
                return this.SemestreBasicoField;
            }
            set {
                if ((this.SemestreBasicoField.Equals(value) != true)) {
                    this.SemestreBasicoField = value;
                    this.RaisePropertyChanged("SemestreBasico");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TipoUsuario {
            get {
                return this.TipoUsuarioField;
            }
            set {
                if ((object.ReferenceEquals(this.TipoUsuarioField, value) != true)) {
                    this.TipoUsuarioField = value;
                    this.RaisePropertyChanged("TipoUsuario");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int TipoUsuarioId {
            get {
                return this.TipoUsuarioIdField;
            }
            set {
                if ((this.TipoUsuarioIdField.Equals(value) != true)) {
                    this.TipoUsuarioIdField = value;
                    this.RaisePropertyChanged("TipoUsuarioId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long UsuarioId {
            get {
                return this.UsuarioIdField;
            }
            set {
                if ((this.UsuarioIdField.Equals(value) != true)) {
                    this.UsuarioIdField = value;
                    this.RaisePropertyChanged("UsuarioId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> nAnotaciones {
            get {
                return this.nAnotacionesField;
            }
            set {
                if ((this.nAnotacionesField.Equals(value) != true)) {
                    this.nAnotacionesField = value;
                    this.RaisePropertyChanged("nAnotaciones");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> nEquipos {
            get {
                return this.nEquiposField;
            }
            set {
                if ((this.nEquiposField.Equals(value) != true)) {
                    this.nEquiposField = value;
                    this.RaisePropertyChanged("nEquipos");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> nMultas {
            get {
                return this.nMultasField;
            }
            set {
                if ((this.nMultasField.Equals(value) != true)) {
                    this.nMultasField = value;
                    this.RaisePropertyChanged("nMultas");
                }
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="PrestamoRecepcionService.IPrestamoRecepcion")]
    public interface IPrestamoRecepcion {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPrestamoRecepcion/getInfoPrestamoRecepcion", ReplyAction="http://tempuri.org/IPrestamoRecepcion/getInfoPrestamoRecepcionResponse")]
        LabManagerCliente.PrestamoRecepcionService.View_PrestamoRecepcion getInfoPrestamoRecepcion(string BarCode);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPrestamoRecepcion/getInfoPrestamoRecepcion", ReplyAction="http://tempuri.org/IPrestamoRecepcion/getInfoPrestamoRecepcionResponse")]
        System.Threading.Tasks.Task<LabManagerCliente.PrestamoRecepcionService.View_PrestamoRecepcion> getInfoPrestamoRecepcionAsync(string BarCode);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPrestamoRecepcion/getRestriccionesEquipo", ReplyAction="http://tempuri.org/IPrestamoRecepcion/getRestriccionesEquipoResponse")]
        LabManagerCliente.PrestamoRecepcionService.RestriccionDto getRestriccionesEquipo(string barCodeEquipo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPrestamoRecepcion/getRestriccionesEquipo", ReplyAction="http://tempuri.org/IPrestamoRecepcion/getRestriccionesEquipoResponse")]
        System.Threading.Tasks.Task<LabManagerCliente.PrestamoRecepcionService.RestriccionDto> getRestriccionesEquipoAsync(string barCodeEquipo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPrestamoRecepcion/PrestarRecibirEquipo", ReplyAction="http://tempuri.org/IPrestamoRecepcion/PrestarRecibirEquipoResponse")]
        LabManagerCliente.PrestamoRecepcionService.View_EquiposACargo PrestarRecibirEquipo(int usuarioId, int auxiliarId, System.Nullable<int> FacultadId, System.Nullable<int> SemestreBasico, string barCodeEquipo, bool operacionManual);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPrestamoRecepcion/PrestarRecibirEquipo", ReplyAction="http://tempuri.org/IPrestamoRecepcion/PrestarRecibirEquipoResponse")]
        System.Threading.Tasks.Task<LabManagerCliente.PrestamoRecepcionService.View_EquiposACargo> PrestarRecibirEquipoAsync(int usuarioId, int auxiliarId, System.Nullable<int> FacultadId, System.Nullable<int> SemestreBasico, string barCodeEquipo, bool operacionManual);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPrestamoRecepcion/getTimeLogOut", ReplyAction="http://tempuri.org/IPrestamoRecepcion/getTimeLogOutResponse")]
        LabManagerCliente.PrestamoRecepcionService.DtoInt getTimeLogOut();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPrestamoRecepcion/getTimeLogOut", ReplyAction="http://tempuri.org/IPrestamoRecepcion/getTimeLogOutResponse")]
        System.Threading.Tasks.Task<LabManagerCliente.PrestamoRecepcionService.DtoInt> getTimeLogOutAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IPrestamoRecepcionChannel : LabManagerCliente.PrestamoRecepcionService.IPrestamoRecepcion, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class PrestamoRecepcionClient : System.ServiceModel.ClientBase<LabManagerCliente.PrestamoRecepcionService.IPrestamoRecepcion>, LabManagerCliente.PrestamoRecepcionService.IPrestamoRecepcion {
        
        public PrestamoRecepcionClient() {
        }
        
        public PrestamoRecepcionClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public PrestamoRecepcionClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public PrestamoRecepcionClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public PrestamoRecepcionClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public LabManagerCliente.PrestamoRecepcionService.View_PrestamoRecepcion getInfoPrestamoRecepcion(string BarCode) {
            return base.Channel.getInfoPrestamoRecepcion(BarCode);
        }
        
        public System.Threading.Tasks.Task<LabManagerCliente.PrestamoRecepcionService.View_PrestamoRecepcion> getInfoPrestamoRecepcionAsync(string BarCode) {
            return base.Channel.getInfoPrestamoRecepcionAsync(BarCode);
        }
        
        public LabManagerCliente.PrestamoRecepcionService.RestriccionDto getRestriccionesEquipo(string barCodeEquipo) {
            return base.Channel.getRestriccionesEquipo(barCodeEquipo);
        }
        
        public System.Threading.Tasks.Task<LabManagerCliente.PrestamoRecepcionService.RestriccionDto> getRestriccionesEquipoAsync(string barCodeEquipo) {
            return base.Channel.getRestriccionesEquipoAsync(barCodeEquipo);
        }
        
        public LabManagerCliente.PrestamoRecepcionService.View_EquiposACargo PrestarRecibirEquipo(int usuarioId, int auxiliarId, System.Nullable<int> FacultadId, System.Nullable<int> SemestreBasico, string barCodeEquipo, bool operacionManual) {
            return base.Channel.PrestarRecibirEquipo(usuarioId, auxiliarId, FacultadId, SemestreBasico, barCodeEquipo, operacionManual);
        }
        
        public System.Threading.Tasks.Task<LabManagerCliente.PrestamoRecepcionService.View_EquiposACargo> PrestarRecibirEquipoAsync(int usuarioId, int auxiliarId, System.Nullable<int> FacultadId, System.Nullable<int> SemestreBasico, string barCodeEquipo, bool operacionManual) {
            return base.Channel.PrestarRecibirEquipoAsync(usuarioId, auxiliarId, FacultadId, SemestreBasico, barCodeEquipo, operacionManual);
        }
        
        public LabManagerCliente.PrestamoRecepcionService.DtoInt getTimeLogOut() {
            return base.Channel.getTimeLogOut();
        }
        
        public System.Threading.Tasks.Task<LabManagerCliente.PrestamoRecepcionService.DtoInt> getTimeLogOutAsync() {
            return base.Channel.getTimeLogOutAsync();
        }
    }
}
