//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LabManagerCliente.AdministradorDocenteService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DtoBase", Namespace="http://schemas.datacontract.org/2004/07/Dtos")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(LabManagerCliente.AdministradorDocenteService.View_Docente))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(LabManagerCliente.AdministradorDocenteService.Lista_View_Facultad))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(LabManagerCliente.AdministradorDocenteService.View_Facultad))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(LabManagerCliente.AdministradorDocenteService.Lista_View_Historial_Docente))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(LabManagerCliente.AdministradorDocenteService.View_Historial_Docente))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(LabManagerCliente.AdministradorDocenteService.Lista_View_Docentes))]
    public partial class DtoBase : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool ErrorField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MensajeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private byte[] TokenField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Error {
            get {
                return this.ErrorField;
            }
            set {
                if ((this.ErrorField.Equals(value) != true)) {
                    this.ErrorField = value;
                    this.RaisePropertyChanged("Error");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Mensaje {
            get {
                return this.MensajeField;
            }
            set {
                if ((object.ReferenceEquals(this.MensajeField, value) != true)) {
                    this.MensajeField = value;
                    this.RaisePropertyChanged("Mensaje");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public byte[] Token {
            get {
                return this.TokenField;
            }
            set {
                if ((object.ReferenceEquals(this.TokenField, value) != true)) {
                    this.TokenField = value;
                    this.RaisePropertyChanged("Token");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="View_Docente", Namespace="http://schemas.datacontract.org/2004/07/Dtos.Basico")]
    [System.SerializableAttribute()]
    public partial class View_Docente : LabManagerCliente.AdministradorDocenteService.DtoBase {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool ActivoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ApellidosField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string BarcodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CreadoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DocumentoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> FacultadIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FacultadNombreField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime FechaCreacionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> FechaModificacionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ModificadoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NombresField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<long> UsuarioCreaIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long UsuarioIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<long> UsuarioModificaIdField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Activo {
            get {
                return this.ActivoField;
            }
            set {
                if ((this.ActivoField.Equals(value) != true)) {
                    this.ActivoField = value;
                    this.RaisePropertyChanged("Activo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Apellidos {
            get {
                return this.ApellidosField;
            }
            set {
                if ((object.ReferenceEquals(this.ApellidosField, value) != true)) {
                    this.ApellidosField = value;
                    this.RaisePropertyChanged("Apellidos");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Barcode {
            get {
                return this.BarcodeField;
            }
            set {
                if ((object.ReferenceEquals(this.BarcodeField, value) != true)) {
                    this.BarcodeField = value;
                    this.RaisePropertyChanged("Barcode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Creado {
            get {
                return this.CreadoField;
            }
            set {
                if ((object.ReferenceEquals(this.CreadoField, value) != true)) {
                    this.CreadoField = value;
                    this.RaisePropertyChanged("Creado");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Documento {
            get {
                return this.DocumentoField;
            }
            set {
                if ((object.ReferenceEquals(this.DocumentoField, value) != true)) {
                    this.DocumentoField = value;
                    this.RaisePropertyChanged("Documento");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> FacultadId {
            get {
                return this.FacultadIdField;
            }
            set {
                if ((this.FacultadIdField.Equals(value) != true)) {
                    this.FacultadIdField = value;
                    this.RaisePropertyChanged("FacultadId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FacultadNombre {
            get {
                return this.FacultadNombreField;
            }
            set {
                if ((object.ReferenceEquals(this.FacultadNombreField, value) != true)) {
                    this.FacultadNombreField = value;
                    this.RaisePropertyChanged("FacultadNombre");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime FechaCreacion {
            get {
                return this.FechaCreacionField;
            }
            set {
                if ((this.FechaCreacionField.Equals(value) != true)) {
                    this.FechaCreacionField = value;
                    this.RaisePropertyChanged("FechaCreacion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> FechaModificacion {
            get {
                return this.FechaModificacionField;
            }
            set {
                if ((this.FechaModificacionField.Equals(value) != true)) {
                    this.FechaModificacionField = value;
                    this.RaisePropertyChanged("FechaModificacion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Modificado {
            get {
                return this.ModificadoField;
            }
            set {
                if ((object.ReferenceEquals(this.ModificadoField, value) != true)) {
                    this.ModificadoField = value;
                    this.RaisePropertyChanged("Modificado");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Nombres {
            get {
                return this.NombresField;
            }
            set {
                if ((object.ReferenceEquals(this.NombresField, value) != true)) {
                    this.NombresField = value;
                    this.RaisePropertyChanged("Nombres");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<long> UsuarioCreaId {
            get {
                return this.UsuarioCreaIdField;
            }
            set {
                if ((this.UsuarioCreaIdField.Equals(value) != true)) {
                    this.UsuarioCreaIdField = value;
                    this.RaisePropertyChanged("UsuarioCreaId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long UsuarioId {
            get {
                return this.UsuarioIdField;
            }
            set {
                if ((this.UsuarioIdField.Equals(value) != true)) {
                    this.UsuarioIdField = value;
                    this.RaisePropertyChanged("UsuarioId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<long> UsuarioModificaId {
            get {
                return this.UsuarioModificaIdField;
            }
            set {
                if ((this.UsuarioModificaIdField.Equals(value) != true)) {
                    this.UsuarioModificaIdField = value;
                    this.RaisePropertyChanged("UsuarioModificaId");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Lista_View_Facultad", Namespace="http://schemas.datacontract.org/2004/07/Dtos.Basico")]
    [System.SerializableAttribute()]
    public partial class Lista_View_Facultad : LabManagerCliente.AdministradorDocenteService.DtoBase {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private LabManagerCliente.AdministradorDocenteService.View_Facultad[] ItemsField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public LabManagerCliente.AdministradorDocenteService.View_Facultad[] Items {
            get {
                return this.ItemsField;
            }
            set {
                if ((object.ReferenceEquals(this.ItemsField, value) != true)) {
                    this.ItemsField = value;
                    this.RaisePropertyChanged("Items");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="View_Facultad", Namespace="http://schemas.datacontract.org/2004/07/Dtos.Basico")]
    [System.SerializableAttribute()]
    public partial class View_Facultad : LabManagerCliente.AdministradorDocenteService.DtoBase {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool ActivoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int CodigoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int FacultadIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime FechaCreacionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> FechaModificacionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NombreField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NombreSedeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UsuarioCreaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long UsuarioCreaIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<long> UsuarioModificaIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UsuarioMoificaField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Activo {
            get {
                return this.ActivoField;
            }
            set {
                if ((this.ActivoField.Equals(value) != true)) {
                    this.ActivoField = value;
                    this.RaisePropertyChanged("Activo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Codigo {
            get {
                return this.CodigoField;
            }
            set {
                if ((this.CodigoField.Equals(value) != true)) {
                    this.CodigoField = value;
                    this.RaisePropertyChanged("Codigo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int FacultadId {
            get {
                return this.FacultadIdField;
            }
            set {
                if ((this.FacultadIdField.Equals(value) != true)) {
                    this.FacultadIdField = value;
                    this.RaisePropertyChanged("FacultadId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime FechaCreacion {
            get {
                return this.FechaCreacionField;
            }
            set {
                if ((this.FechaCreacionField.Equals(value) != true)) {
                    this.FechaCreacionField = value;
                    this.RaisePropertyChanged("FechaCreacion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> FechaModificacion {
            get {
                return this.FechaModificacionField;
            }
            set {
                if ((this.FechaModificacionField.Equals(value) != true)) {
                    this.FechaModificacionField = value;
                    this.RaisePropertyChanged("FechaModificacion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Nombre {
            get {
                return this.NombreField;
            }
            set {
                if ((object.ReferenceEquals(this.NombreField, value) != true)) {
                    this.NombreField = value;
                    this.RaisePropertyChanged("Nombre");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NombreSede {
            get {
                return this.NombreSedeField;
            }
            set {
                if ((object.ReferenceEquals(this.NombreSedeField, value) != true)) {
                    this.NombreSedeField = value;
                    this.RaisePropertyChanged("NombreSede");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string UsuarioCrea {
            get {
                return this.UsuarioCreaField;
            }
            set {
                if ((object.ReferenceEquals(this.UsuarioCreaField, value) != true)) {
                    this.UsuarioCreaField = value;
                    this.RaisePropertyChanged("UsuarioCrea");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long UsuarioCreaId {
            get {
                return this.UsuarioCreaIdField;
            }
            set {
                if ((this.UsuarioCreaIdField.Equals(value) != true)) {
                    this.UsuarioCreaIdField = value;
                    this.RaisePropertyChanged("UsuarioCreaId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<long> UsuarioModificaId {
            get {
                return this.UsuarioModificaIdField;
            }
            set {
                if ((this.UsuarioModificaIdField.Equals(value) != true)) {
                    this.UsuarioModificaIdField = value;
                    this.RaisePropertyChanged("UsuarioModificaId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string UsuarioMoifica {
            get {
                return this.UsuarioMoificaField;
            }
            set {
                if ((object.ReferenceEquals(this.UsuarioMoificaField, value) != true)) {
                    this.UsuarioMoificaField = value;
                    this.RaisePropertyChanged("UsuarioMoifica");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Lista_View_Historial_Docente", Namespace="http://schemas.datacontract.org/2004/07/Dtos.Basico")]
    [System.SerializableAttribute()]
    public partial class Lista_View_Historial_Docente : LabManagerCliente.AdministradorDocenteService.DtoBase {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private LabManagerCliente.AdministradorDocenteService.View_Historial_Docente[] ItemsField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public LabManagerCliente.AdministradorDocenteService.View_Historial_Docente[] Items {
            get {
                return this.ItemsField;
            }
            set {
                if ((object.ReferenceEquals(this.ItemsField, value) != true)) {
                    this.ItemsField = value;
                    this.RaisePropertyChanged("Items");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="View_Historial_Docente", Namespace="http://schemas.datacontract.org/2004/07/Dtos.Basico")]
    [System.SerializableAttribute()]
    public partial class View_Historial_Docente : LabManagerCliente.AdministradorDocenteService.DtoBase {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CodigoInventarioField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CodigoLaboratorioField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescripcionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long EquipoIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime FechaPrestamoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> FechaRecepcionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MarcaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long PrestamorecepcionIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> TipoEquipoIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long UsuarioIdField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CodigoInventario {
            get {
                return this.CodigoInventarioField;
            }
            set {
                if ((object.ReferenceEquals(this.CodigoInventarioField, value) != true)) {
                    this.CodigoInventarioField = value;
                    this.RaisePropertyChanged("CodigoInventario");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CodigoLaboratorio {
            get {
                return this.CodigoLaboratorioField;
            }
            set {
                if ((object.ReferenceEquals(this.CodigoLaboratorioField, value) != true)) {
                    this.CodigoLaboratorioField = value;
                    this.RaisePropertyChanged("CodigoLaboratorio");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Descripcion {
            get {
                return this.DescripcionField;
            }
            set {
                if ((object.ReferenceEquals(this.DescripcionField, value) != true)) {
                    this.DescripcionField = value;
                    this.RaisePropertyChanged("Descripcion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long EquipoId {
            get {
                return this.EquipoIdField;
            }
            set {
                if ((this.EquipoIdField.Equals(value) != true)) {
                    this.EquipoIdField = value;
                    this.RaisePropertyChanged("EquipoId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime FechaPrestamo {
            get {
                return this.FechaPrestamoField;
            }
            set {
                if ((this.FechaPrestamoField.Equals(value) != true)) {
                    this.FechaPrestamoField = value;
                    this.RaisePropertyChanged("FechaPrestamo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> FechaRecepcion {
            get {
                return this.FechaRecepcionField;
            }
            set {
                if ((this.FechaRecepcionField.Equals(value) != true)) {
                    this.FechaRecepcionField = value;
                    this.RaisePropertyChanged("FechaRecepcion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Marca {
            get {
                return this.MarcaField;
            }
            set {
                if ((object.ReferenceEquals(this.MarcaField, value) != true)) {
                    this.MarcaField = value;
                    this.RaisePropertyChanged("Marca");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long PrestamorecepcionId {
            get {
                return this.PrestamorecepcionIdField;
            }
            set {
                if ((this.PrestamorecepcionIdField.Equals(value) != true)) {
                    this.PrestamorecepcionIdField = value;
                    this.RaisePropertyChanged("PrestamorecepcionId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> TipoEquipoId {
            get {
                return this.TipoEquipoIdField;
            }
            set {
                if ((this.TipoEquipoIdField.Equals(value) != true)) {
                    this.TipoEquipoIdField = value;
                    this.RaisePropertyChanged("TipoEquipoId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long UsuarioId {
            get {
                return this.UsuarioIdField;
            }
            set {
                if ((this.UsuarioIdField.Equals(value) != true)) {
                    this.UsuarioIdField = value;
                    this.RaisePropertyChanged("UsuarioId");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Lista_View_Docentes", Namespace="http://schemas.datacontract.org/2004/07/Dtos.Basico")]
    [System.SerializableAttribute()]
    public partial class Lista_View_Docentes : LabManagerCliente.AdministradorDocenteService.DtoBase {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private LabManagerCliente.AdministradorDocenteService.View_Docente[] ItemsField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public LabManagerCliente.AdministradorDocenteService.View_Docente[] Items {
            get {
                return this.ItemsField;
            }
            set {
                if ((object.ReferenceEquals(this.ItemsField, value) != true)) {
                    this.ItemsField = value;
                    this.RaisePropertyChanged("Items");
                }
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="AdministradorDocenteService.IAdministradorDocente")]
    public interface IAdministradorDocente {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAdministradorDocente/getDocentes", ReplyAction="http://tempuri.org/IAdministradorDocente/getDocentesResponse")]
        LabManagerCliente.AdministradorDocenteService.Lista_View_Docentes getDocentes(string FiltroTexto, System.Nullable<bool> Activo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAdministradorDocente/getDocentes", ReplyAction="http://tempuri.org/IAdministradorDocente/getDocentesResponse")]
        System.Threading.Tasks.Task<LabManagerCliente.AdministradorDocenteService.Lista_View_Docentes> getDocentesAsync(string FiltroTexto, System.Nullable<bool> Activo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAdministradorDocente/AddDocente", ReplyAction="http://tempuri.org/IAdministradorDocente/AddDocenteResponse")]
        LabManagerCliente.AdministradorDocenteService.DtoBase AddDocente(LabManagerCliente.AdministradorDocenteService.View_Docente newDocente);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAdministradorDocente/AddDocente", ReplyAction="http://tempuri.org/IAdministradorDocente/AddDocenteResponse")]
        System.Threading.Tasks.Task<LabManagerCliente.AdministradorDocenteService.DtoBase> AddDocenteAsync(LabManagerCliente.AdministradorDocenteService.View_Docente newDocente);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAdministradorDocente/EditDocente", ReplyAction="http://tempuri.org/IAdministradorDocente/EditDocenteResponse")]
        LabManagerCliente.AdministradorDocenteService.DtoBase EditDocente([System.ServiceModel.MessageParameterAttribute(Name="editDocente")] LabManagerCliente.AdministradorDocenteService.View_Docente editDocente1);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAdministradorDocente/EditDocente", ReplyAction="http://tempuri.org/IAdministradorDocente/EditDocenteResponse")]
        System.Threading.Tasks.Task<LabManagerCliente.AdministradorDocenteService.DtoBase> EditDocenteAsync(LabManagerCliente.AdministradorDocenteService.View_Docente editDocente);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAdministradorDocente/getFacultad", ReplyAction="http://tempuri.org/IAdministradorDocente/getFacultadResponse")]
        LabManagerCliente.AdministradorDocenteService.Lista_View_Facultad getFacultad(string FiltroTexto, System.Nullable<bool> Activo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAdministradorDocente/getFacultad", ReplyAction="http://tempuri.org/IAdministradorDocente/getFacultadResponse")]
        System.Threading.Tasks.Task<LabManagerCliente.AdministradorDocenteService.Lista_View_Facultad> getFacultadAsync(string FiltroTexto, System.Nullable<bool> Activo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAdministradorDocente/getHistorialBasico", ReplyAction="http://tempuri.org/IAdministradorDocente/getHistorialBasicoResponse")]
        LabManagerCliente.AdministradorDocenteService.Lista_View_Historial_Docente getHistorialBasico(long UsuarioId, System.DateTime FechaInicio, System.DateTime FechaFin);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAdministradorDocente/getHistorialBasico", ReplyAction="http://tempuri.org/IAdministradorDocente/getHistorialBasicoResponse")]
        System.Threading.Tasks.Task<LabManagerCliente.AdministradorDocenteService.Lista_View_Historial_Docente> getHistorialBasicoAsync(long UsuarioId, System.DateTime FechaInicio, System.DateTime FechaFin);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IAdministradorDocenteChannel : LabManagerCliente.AdministradorDocenteService.IAdministradorDocente, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class AdministradorDocenteClient : System.ServiceModel.ClientBase<LabManagerCliente.AdministradorDocenteService.IAdministradorDocente>, LabManagerCliente.AdministradorDocenteService.IAdministradorDocente {
        
        public AdministradorDocenteClient() {
        }
        
        public AdministradorDocenteClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public AdministradorDocenteClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AdministradorDocenteClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AdministradorDocenteClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public LabManagerCliente.AdministradorDocenteService.Lista_View_Docentes getDocentes(string FiltroTexto, System.Nullable<bool> Activo) {
            return base.Channel.getDocentes(FiltroTexto, Activo);
        }
        
        public System.Threading.Tasks.Task<LabManagerCliente.AdministradorDocenteService.Lista_View_Docentes> getDocentesAsync(string FiltroTexto, System.Nullable<bool> Activo) {
            return base.Channel.getDocentesAsync(FiltroTexto, Activo);
        }
        
        public LabManagerCliente.AdministradorDocenteService.DtoBase AddDocente(LabManagerCliente.AdministradorDocenteService.View_Docente newDocente) {
            return base.Channel.AddDocente(newDocente);
        }
        
        public System.Threading.Tasks.Task<LabManagerCliente.AdministradorDocenteService.DtoBase> AddDocenteAsync(LabManagerCliente.AdministradorDocenteService.View_Docente newDocente) {
            return base.Channel.AddDocenteAsync(newDocente);
        }
        
        public LabManagerCliente.AdministradorDocenteService.DtoBase EditDocente(LabManagerCliente.AdministradorDocenteService.View_Docente editDocente1) {
            return base.Channel.EditDocente(editDocente1);
        }
        
        public System.Threading.Tasks.Task<LabManagerCliente.AdministradorDocenteService.DtoBase> EditDocenteAsync(LabManagerCliente.AdministradorDocenteService.View_Docente editDocente) {
            return base.Channel.EditDocenteAsync(editDocente);
        }
        
        public LabManagerCliente.AdministradorDocenteService.Lista_View_Facultad getFacultad(string FiltroTexto, System.Nullable<bool> Activo) {
            return base.Channel.getFacultad(FiltroTexto, Activo);
        }
        
        public System.Threading.Tasks.Task<LabManagerCliente.AdministradorDocenteService.Lista_View_Facultad> getFacultadAsync(string FiltroTexto, System.Nullable<bool> Activo) {
            return base.Channel.getFacultadAsync(FiltroTexto, Activo);
        }
        
        public LabManagerCliente.AdministradorDocenteService.Lista_View_Historial_Docente getHistorialBasico(long UsuarioId, System.DateTime FechaInicio, System.DateTime FechaFin) {
            return base.Channel.getHistorialBasico(UsuarioId, FechaInicio, FechaFin);
        }
        
        public System.Threading.Tasks.Task<LabManagerCliente.AdministradorDocenteService.Lista_View_Historial_Docente> getHistorialBasicoAsync(long UsuarioId, System.DateTime FechaInicio, System.DateTime FechaFin) {
            return base.Channel.getHistorialBasicoAsync(UsuarioId, FechaInicio, FechaFin);
        }
    }
}
