//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LabManagerCliente.AdministradorFacultadService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DtoBase", Namespace="http://schemas.datacontract.org/2004/07/Dtos")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(LabManagerCliente.AdministradorFacultadService.View_Facultad))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(LabManagerCliente.AdministradorFacultadService.Lista_View_Facultad))]
    public partial class DtoBase : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool ErrorField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MensajeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private byte[] TokenField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Error {
            get {
                return this.ErrorField;
            }
            set {
                if ((this.ErrorField.Equals(value) != true)) {
                    this.ErrorField = value;
                    this.RaisePropertyChanged("Error");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Mensaje {
            get {
                return this.MensajeField;
            }
            set {
                if ((object.ReferenceEquals(this.MensajeField, value) != true)) {
                    this.MensajeField = value;
                    this.RaisePropertyChanged("Mensaje");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public byte[] Token {
            get {
                return this.TokenField;
            }
            set {
                if ((object.ReferenceEquals(this.TokenField, value) != true)) {
                    this.TokenField = value;
                    this.RaisePropertyChanged("Token");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="View_Facultad", Namespace="http://schemas.datacontract.org/2004/07/Dtos.Basico")]
    [System.SerializableAttribute()]
    public partial class View_Facultad : LabManagerCliente.AdministradorFacultadService.DtoBase {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool ActivoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int CodigoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int FacultadIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime FechaCreacionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> FechaModificacionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NombreField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NombreSedeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> SedeIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UsuarioCreaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long UsuarioCreaIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<long> UsuarioModificaIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UsuarioMoificaField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Activo {
            get {
                return this.ActivoField;
            }
            set {
                if ((this.ActivoField.Equals(value) != true)) {
                    this.ActivoField = value;
                    this.RaisePropertyChanged("Activo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Codigo {
            get {
                return this.CodigoField;
            }
            set {
                if ((this.CodigoField.Equals(value) != true)) {
                    this.CodigoField = value;
                    this.RaisePropertyChanged("Codigo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int FacultadId {
            get {
                return this.FacultadIdField;
            }
            set {
                if ((this.FacultadIdField.Equals(value) != true)) {
                    this.FacultadIdField = value;
                    this.RaisePropertyChanged("FacultadId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime FechaCreacion {
            get {
                return this.FechaCreacionField;
            }
            set {
                if ((this.FechaCreacionField.Equals(value) != true)) {
                    this.FechaCreacionField = value;
                    this.RaisePropertyChanged("FechaCreacion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> FechaModificacion {
            get {
                return this.FechaModificacionField;
            }
            set {
                if ((this.FechaModificacionField.Equals(value) != true)) {
                    this.FechaModificacionField = value;
                    this.RaisePropertyChanged("FechaModificacion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Nombre {
            get {
                return this.NombreField;
            }
            set {
                if ((object.ReferenceEquals(this.NombreField, value) != true)) {
                    this.NombreField = value;
                    this.RaisePropertyChanged("Nombre");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NombreSede {
            get {
                return this.NombreSedeField;
            }
            set {
                if ((object.ReferenceEquals(this.NombreSedeField, value) != true)) {
                    this.NombreSedeField = value;
                    this.RaisePropertyChanged("NombreSede");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> SedeId {
            get {
                return this.SedeIdField;
            }
            set {
                if ((this.SedeIdField.Equals(value) != true)) {
                    this.SedeIdField = value;
                    this.RaisePropertyChanged("SedeId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string UsuarioCrea {
            get {
                return this.UsuarioCreaField;
            }
            set {
                if ((object.ReferenceEquals(this.UsuarioCreaField, value) != true)) {
                    this.UsuarioCreaField = value;
                    this.RaisePropertyChanged("UsuarioCrea");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long UsuarioCreaId {
            get {
                return this.UsuarioCreaIdField;
            }
            set {
                if ((this.UsuarioCreaIdField.Equals(value) != true)) {
                    this.UsuarioCreaIdField = value;
                    this.RaisePropertyChanged("UsuarioCreaId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<long> UsuarioModificaId {
            get {
                return this.UsuarioModificaIdField;
            }
            set {
                if ((this.UsuarioModificaIdField.Equals(value) != true)) {
                    this.UsuarioModificaIdField = value;
                    this.RaisePropertyChanged("UsuarioModificaId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string UsuarioMoifica {
            get {
                return this.UsuarioMoificaField;
            }
            set {
                if ((object.ReferenceEquals(this.UsuarioMoificaField, value) != true)) {
                    this.UsuarioMoificaField = value;
                    this.RaisePropertyChanged("UsuarioMoifica");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Lista_View_Facultad", Namespace="http://schemas.datacontract.org/2004/07/Dtos.Basico")]
    [System.SerializableAttribute()]
    public partial class Lista_View_Facultad : LabManagerCliente.AdministradorFacultadService.DtoBase {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private LabManagerCliente.AdministradorFacultadService.View_Facultad[] ItemsField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public LabManagerCliente.AdministradorFacultadService.View_Facultad[] Items {
            get {
                return this.ItemsField;
            }
            set {
                if ((object.ReferenceEquals(this.ItemsField, value) != true)) {
                    this.ItemsField = value;
                    this.RaisePropertyChanged("Items");
                }
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="AdministradorFacultadService.IAdministradorFacultad")]
    public interface IAdministradorFacultad {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAdministradorFacultad/getFacultad", ReplyAction="http://tempuri.org/IAdministradorFacultad/getFacultadResponse")]
        LabManagerCliente.AdministradorFacultadService.Lista_View_Facultad getFacultad(string FiltroTexto, System.Nullable<bool> Activo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAdministradorFacultad/getFacultad", ReplyAction="http://tempuri.org/IAdministradorFacultad/getFacultadResponse")]
        System.Threading.Tasks.Task<LabManagerCliente.AdministradorFacultadService.Lista_View_Facultad> getFacultadAsync(string FiltroTexto, System.Nullable<bool> Activo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAdministradorFacultad/AddFacultad", ReplyAction="http://tempuri.org/IAdministradorFacultad/AddFacultadResponse")]
        LabManagerCliente.AdministradorFacultadService.DtoBase AddFacultad(LabManagerCliente.AdministradorFacultadService.View_Facultad newFacultad);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAdministradorFacultad/AddFacultad", ReplyAction="http://tempuri.org/IAdministradorFacultad/AddFacultadResponse")]
        System.Threading.Tasks.Task<LabManagerCliente.AdministradorFacultadService.DtoBase> AddFacultadAsync(LabManagerCliente.AdministradorFacultadService.View_Facultad newFacultad);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAdministradorFacultad/EditFacultad", ReplyAction="http://tempuri.org/IAdministradorFacultad/EditFacultadResponse")]
        LabManagerCliente.AdministradorFacultadService.DtoBase EditFacultad([System.ServiceModel.MessageParameterAttribute(Name="editFacultad")] LabManagerCliente.AdministradorFacultadService.View_Facultad editFacultad1);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAdministradorFacultad/EditFacultad", ReplyAction="http://tempuri.org/IAdministradorFacultad/EditFacultadResponse")]
        System.Threading.Tasks.Task<LabManagerCliente.AdministradorFacultadService.DtoBase> EditFacultadAsync(LabManagerCliente.AdministradorFacultadService.View_Facultad editFacultad);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IAdministradorFacultadChannel : LabManagerCliente.AdministradorFacultadService.IAdministradorFacultad, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class AdministradorFacultadClient : System.ServiceModel.ClientBase<LabManagerCliente.AdministradorFacultadService.IAdministradorFacultad>, LabManagerCliente.AdministradorFacultadService.IAdministradorFacultad {
        
        public AdministradorFacultadClient() {
        }
        
        public AdministradorFacultadClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public AdministradorFacultadClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AdministradorFacultadClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AdministradorFacultadClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public LabManagerCliente.AdministradorFacultadService.Lista_View_Facultad getFacultad(string FiltroTexto, System.Nullable<bool> Activo) {
            return base.Channel.getFacultad(FiltroTexto, Activo);
        }
        
        public System.Threading.Tasks.Task<LabManagerCliente.AdministradorFacultadService.Lista_View_Facultad> getFacultadAsync(string FiltroTexto, System.Nullable<bool> Activo) {
            return base.Channel.getFacultadAsync(FiltroTexto, Activo);
        }
        
        public LabManagerCliente.AdministradorFacultadService.DtoBase AddFacultad(LabManagerCliente.AdministradorFacultadService.View_Facultad newFacultad) {
            return base.Channel.AddFacultad(newFacultad);
        }
        
        public System.Threading.Tasks.Task<LabManagerCliente.AdministradorFacultadService.DtoBase> AddFacultadAsync(LabManagerCliente.AdministradorFacultadService.View_Facultad newFacultad) {
            return base.Channel.AddFacultadAsync(newFacultad);
        }
        
        public LabManagerCliente.AdministradorFacultadService.DtoBase EditFacultad(LabManagerCliente.AdministradorFacultadService.View_Facultad editFacultad1) {
            return base.Channel.EditFacultad(editFacultad1);
        }
        
        public System.Threading.Tasks.Task<LabManagerCliente.AdministradorFacultadService.DtoBase> EditFacultadAsync(LabManagerCliente.AdministradorFacultadService.View_Facultad editFacultad) {
            return base.Channel.EditFacultadAsync(editFacultad);
        }
    }
}
