//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LabManagerCliente.AdministradorAuxiliarService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DtoBase", Namespace="http://schemas.datacontract.org/2004/07/Dtos")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(LabManagerCliente.AdministradorAuxiliarService.View_Auxiliar))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(LabManagerCliente.AdministradorAuxiliarService.Lista_View_Auxiliar_Activo))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(LabManagerCliente.AdministradorAuxiliarService.View_Auxiliar_Activo))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(LabManagerCliente.AdministradorAuxiliarService.Lista_View_Auxiliar))]
    public partial class DtoBase : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool ErrorField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MensajeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private byte[] TokenField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Error {
            get {
                return this.ErrorField;
            }
            set {
                if ((this.ErrorField.Equals(value) != true)) {
                    this.ErrorField = value;
                    this.RaisePropertyChanged("Error");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Mensaje {
            get {
                return this.MensajeField;
            }
            set {
                if ((object.ReferenceEquals(this.MensajeField, value) != true)) {
                    this.MensajeField = value;
                    this.RaisePropertyChanged("Mensaje");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public byte[] Token {
            get {
                return this.TokenField;
            }
            set {
                if ((object.ReferenceEquals(this.TokenField, value) != true)) {
                    this.TokenField = value;
                    this.RaisePropertyChanged("Token");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="View_Auxiliar", Namespace="http://schemas.datacontract.org/2004/07/Dtos.Basico")]
    [System.SerializableAttribute()]
    public partial class View_Auxiliar : LabManagerCliente.AdministradorAuxiliarService.DtoBase {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool ActivoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ApellidosField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string BarcodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CorreoElectronicoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CreadoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DocumentoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime FechaCreacionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> FechaModificacionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ModificadoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NombresField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PasswordField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<long> UsuarioCreaIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long UsuarioIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<long> UsuarioModificaIdField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Activo {
            get {
                return this.ActivoField;
            }
            set {
                if ((this.ActivoField.Equals(value) != true)) {
                    this.ActivoField = value;
                    this.RaisePropertyChanged("Activo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Apellidos {
            get {
                return this.ApellidosField;
            }
            set {
                if ((object.ReferenceEquals(this.ApellidosField, value) != true)) {
                    this.ApellidosField = value;
                    this.RaisePropertyChanged("Apellidos");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Barcode {
            get {
                return this.BarcodeField;
            }
            set {
                if ((object.ReferenceEquals(this.BarcodeField, value) != true)) {
                    this.BarcodeField = value;
                    this.RaisePropertyChanged("Barcode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CorreoElectronico {
            get {
                return this.CorreoElectronicoField;
            }
            set {
                if ((object.ReferenceEquals(this.CorreoElectronicoField, value) != true)) {
                    this.CorreoElectronicoField = value;
                    this.RaisePropertyChanged("CorreoElectronico");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Creado {
            get {
                return this.CreadoField;
            }
            set {
                if ((object.ReferenceEquals(this.CreadoField, value) != true)) {
                    this.CreadoField = value;
                    this.RaisePropertyChanged("Creado");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Documento {
            get {
                return this.DocumentoField;
            }
            set {
                if ((object.ReferenceEquals(this.DocumentoField, value) != true)) {
                    this.DocumentoField = value;
                    this.RaisePropertyChanged("Documento");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime FechaCreacion {
            get {
                return this.FechaCreacionField;
            }
            set {
                if ((this.FechaCreacionField.Equals(value) != true)) {
                    this.FechaCreacionField = value;
                    this.RaisePropertyChanged("FechaCreacion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> FechaModificacion {
            get {
                return this.FechaModificacionField;
            }
            set {
                if ((this.FechaModificacionField.Equals(value) != true)) {
                    this.FechaModificacionField = value;
                    this.RaisePropertyChanged("FechaModificacion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Modificado {
            get {
                return this.ModificadoField;
            }
            set {
                if ((object.ReferenceEquals(this.ModificadoField, value) != true)) {
                    this.ModificadoField = value;
                    this.RaisePropertyChanged("Modificado");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Nombres {
            get {
                return this.NombresField;
            }
            set {
                if ((object.ReferenceEquals(this.NombresField, value) != true)) {
                    this.NombresField = value;
                    this.RaisePropertyChanged("Nombres");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Password {
            get {
                return this.PasswordField;
            }
            set {
                if ((object.ReferenceEquals(this.PasswordField, value) != true)) {
                    this.PasswordField = value;
                    this.RaisePropertyChanged("Password");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<long> UsuarioCreaId {
            get {
                return this.UsuarioCreaIdField;
            }
            set {
                if ((this.UsuarioCreaIdField.Equals(value) != true)) {
                    this.UsuarioCreaIdField = value;
                    this.RaisePropertyChanged("UsuarioCreaId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long UsuarioId {
            get {
                return this.UsuarioIdField;
            }
            set {
                if ((this.UsuarioIdField.Equals(value) != true)) {
                    this.UsuarioIdField = value;
                    this.RaisePropertyChanged("UsuarioId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<long> UsuarioModificaId {
            get {
                return this.UsuarioModificaIdField;
            }
            set {
                if ((this.UsuarioModificaIdField.Equals(value) != true)) {
                    this.UsuarioModificaIdField = value;
                    this.RaisePropertyChanged("UsuarioModificaId");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Lista_View_Auxiliar_Activo", Namespace="http://schemas.datacontract.org/2004/07/Dtos.Basico")]
    [System.SerializableAttribute()]
    public partial class Lista_View_Auxiliar_Activo : LabManagerCliente.AdministradorAuxiliarService.DtoBase {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private LabManagerCliente.AdministradorAuxiliarService.View_Auxiliar_Activo[] ItemsField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public LabManagerCliente.AdministradorAuxiliarService.View_Auxiliar_Activo[] Items {
            get {
                return this.ItemsField;
            }
            set {
                if ((object.ReferenceEquals(this.ItemsField, value) != true)) {
                    this.ItemsField = value;
                    this.RaisePropertyChanged("Items");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="View_Auxiliar_Activo", Namespace="http://schemas.datacontract.org/2004/07/Dtos.Basico")]
    [System.SerializableAttribute()]
    public partial class View_Auxiliar_Activo : LabManagerCliente.AdministradorAuxiliarService.DtoBase {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool ActivoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ApellidosField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string BarcodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CorreoElectronicoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CreadoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DocumentoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime FechaCreacionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> FechaModificacionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ModificadoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NombresField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PasswordField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TextoCortoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<long> UsuarioCreaIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long UsuarioIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<long> UsuarioModificaIdField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Activo {
            get {
                return this.ActivoField;
            }
            set {
                if ((this.ActivoField.Equals(value) != true)) {
                    this.ActivoField = value;
                    this.RaisePropertyChanged("Activo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Apellidos {
            get {
                return this.ApellidosField;
            }
            set {
                if ((object.ReferenceEquals(this.ApellidosField, value) != true)) {
                    this.ApellidosField = value;
                    this.RaisePropertyChanged("Apellidos");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Barcode {
            get {
                return this.BarcodeField;
            }
            set {
                if ((object.ReferenceEquals(this.BarcodeField, value) != true)) {
                    this.BarcodeField = value;
                    this.RaisePropertyChanged("Barcode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CorreoElectronico {
            get {
                return this.CorreoElectronicoField;
            }
            set {
                if ((object.ReferenceEquals(this.CorreoElectronicoField, value) != true)) {
                    this.CorreoElectronicoField = value;
                    this.RaisePropertyChanged("CorreoElectronico");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Creado {
            get {
                return this.CreadoField;
            }
            set {
                if ((object.ReferenceEquals(this.CreadoField, value) != true)) {
                    this.CreadoField = value;
                    this.RaisePropertyChanged("Creado");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Documento {
            get {
                return this.DocumentoField;
            }
            set {
                if ((object.ReferenceEquals(this.DocumentoField, value) != true)) {
                    this.DocumentoField = value;
                    this.RaisePropertyChanged("Documento");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime FechaCreacion {
            get {
                return this.FechaCreacionField;
            }
            set {
                if ((this.FechaCreacionField.Equals(value) != true)) {
                    this.FechaCreacionField = value;
                    this.RaisePropertyChanged("FechaCreacion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> FechaModificacion {
            get {
                return this.FechaModificacionField;
            }
            set {
                if ((this.FechaModificacionField.Equals(value) != true)) {
                    this.FechaModificacionField = value;
                    this.RaisePropertyChanged("FechaModificacion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Modificado {
            get {
                return this.ModificadoField;
            }
            set {
                if ((object.ReferenceEquals(this.ModificadoField, value) != true)) {
                    this.ModificadoField = value;
                    this.RaisePropertyChanged("Modificado");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Nombres {
            get {
                return this.NombresField;
            }
            set {
                if ((object.ReferenceEquals(this.NombresField, value) != true)) {
                    this.NombresField = value;
                    this.RaisePropertyChanged("Nombres");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Password {
            get {
                return this.PasswordField;
            }
            set {
                if ((object.ReferenceEquals(this.PasswordField, value) != true)) {
                    this.PasswordField = value;
                    this.RaisePropertyChanged("Password");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TextoCorto {
            get {
                return this.TextoCortoField;
            }
            set {
                if ((object.ReferenceEquals(this.TextoCortoField, value) != true)) {
                    this.TextoCortoField = value;
                    this.RaisePropertyChanged("TextoCorto");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<long> UsuarioCreaId {
            get {
                return this.UsuarioCreaIdField;
            }
            set {
                if ((this.UsuarioCreaIdField.Equals(value) != true)) {
                    this.UsuarioCreaIdField = value;
                    this.RaisePropertyChanged("UsuarioCreaId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long UsuarioId {
            get {
                return this.UsuarioIdField;
            }
            set {
                if ((this.UsuarioIdField.Equals(value) != true)) {
                    this.UsuarioIdField = value;
                    this.RaisePropertyChanged("UsuarioId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<long> UsuarioModificaId {
            get {
                return this.UsuarioModificaIdField;
            }
            set {
                if ((this.UsuarioModificaIdField.Equals(value) != true)) {
                    this.UsuarioModificaIdField = value;
                    this.RaisePropertyChanged("UsuarioModificaId");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Lista_View_Auxiliar", Namespace="http://schemas.datacontract.org/2004/07/Dtos.Basico")]
    [System.SerializableAttribute()]
    public partial class Lista_View_Auxiliar : LabManagerCliente.AdministradorAuxiliarService.DtoBase {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private LabManagerCliente.AdministradorAuxiliarService.View_Auxiliar[] ItemsField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public LabManagerCliente.AdministradorAuxiliarService.View_Auxiliar[] Items {
            get {
                return this.ItemsField;
            }
            set {
                if ((object.ReferenceEquals(this.ItemsField, value) != true)) {
                    this.ItemsField = value;
                    this.RaisePropertyChanged("Items");
                }
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="AdministradorAuxiliarService.IAdministradorAuxiliar")]
    public interface IAdministradorAuxiliar {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAdministradorAuxiliar/getAuxiliares", ReplyAction="http://tempuri.org/IAdministradorAuxiliar/getAuxiliaresResponse")]
        LabManagerCliente.AdministradorAuxiliarService.Lista_View_Auxiliar getAuxiliares(string FiltroTexto, System.Nullable<bool> Activo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAdministradorAuxiliar/getAuxiliares", ReplyAction="http://tempuri.org/IAdministradorAuxiliar/getAuxiliaresResponse")]
        System.Threading.Tasks.Task<LabManagerCliente.AdministradorAuxiliarService.Lista_View_Auxiliar> getAuxiliaresAsync(string FiltroTexto, System.Nullable<bool> Activo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAdministradorAuxiliar/getAuxiliaresActivos", ReplyAction="http://tempuri.org/IAdministradorAuxiliar/getAuxiliaresActivosResponse")]
        LabManagerCliente.AdministradorAuxiliarService.Lista_View_Auxiliar_Activo getAuxiliaresActivos();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAdministradorAuxiliar/getAuxiliaresActivos", ReplyAction="http://tempuri.org/IAdministradorAuxiliar/getAuxiliaresActivosResponse")]
        System.Threading.Tasks.Task<LabManagerCliente.AdministradorAuxiliarService.Lista_View_Auxiliar_Activo> getAuxiliaresActivosAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAdministradorAuxiliar/AddAuxiliar", ReplyAction="http://tempuri.org/IAdministradorAuxiliar/AddAuxiliarResponse")]
        LabManagerCliente.AdministradorAuxiliarService.DtoBase AddAuxiliar(LabManagerCliente.AdministradorAuxiliarService.View_Auxiliar newAuxiliar);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAdministradorAuxiliar/AddAuxiliar", ReplyAction="http://tempuri.org/IAdministradorAuxiliar/AddAuxiliarResponse")]
        System.Threading.Tasks.Task<LabManagerCliente.AdministradorAuxiliarService.DtoBase> AddAuxiliarAsync(LabManagerCliente.AdministradorAuxiliarService.View_Auxiliar newAuxiliar);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAdministradorAuxiliar/EditAuxiliar", ReplyAction="http://tempuri.org/IAdministradorAuxiliar/EditAuxiliarResponse")]
        LabManagerCliente.AdministradorAuxiliarService.DtoBase EditAuxiliar([System.ServiceModel.MessageParameterAttribute(Name="editAuxiliar")] LabManagerCliente.AdministradorAuxiliarService.View_Auxiliar editAuxiliar1);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAdministradorAuxiliar/EditAuxiliar", ReplyAction="http://tempuri.org/IAdministradorAuxiliar/EditAuxiliarResponse")]
        System.Threading.Tasks.Task<LabManagerCliente.AdministradorAuxiliarService.DtoBase> EditAuxiliarAsync(LabManagerCliente.AdministradorAuxiliarService.View_Auxiliar editAuxiliar);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IAdministradorAuxiliarChannel : LabManagerCliente.AdministradorAuxiliarService.IAdministradorAuxiliar, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class AdministradorAuxiliarClient : System.ServiceModel.ClientBase<LabManagerCliente.AdministradorAuxiliarService.IAdministradorAuxiliar>, LabManagerCliente.AdministradorAuxiliarService.IAdministradorAuxiliar {
        
        public AdministradorAuxiliarClient() {
        }
        
        public AdministradorAuxiliarClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public AdministradorAuxiliarClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AdministradorAuxiliarClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AdministradorAuxiliarClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public LabManagerCliente.AdministradorAuxiliarService.Lista_View_Auxiliar getAuxiliares(string FiltroTexto, System.Nullable<bool> Activo) {
            return base.Channel.getAuxiliares(FiltroTexto, Activo);
        }
        
        public System.Threading.Tasks.Task<LabManagerCliente.AdministradorAuxiliarService.Lista_View_Auxiliar> getAuxiliaresAsync(string FiltroTexto, System.Nullable<bool> Activo) {
            return base.Channel.getAuxiliaresAsync(FiltroTexto, Activo);
        }
        
        public LabManagerCliente.AdministradorAuxiliarService.Lista_View_Auxiliar_Activo getAuxiliaresActivos() {
            return base.Channel.getAuxiliaresActivos();
        }
        
        public System.Threading.Tasks.Task<LabManagerCliente.AdministradorAuxiliarService.Lista_View_Auxiliar_Activo> getAuxiliaresActivosAsync() {
            return base.Channel.getAuxiliaresActivosAsync();
        }
        
        public LabManagerCliente.AdministradorAuxiliarService.DtoBase AddAuxiliar(LabManagerCliente.AdministradorAuxiliarService.View_Auxiliar newAuxiliar) {
            return base.Channel.AddAuxiliar(newAuxiliar);
        }
        
        public System.Threading.Tasks.Task<LabManagerCliente.AdministradorAuxiliarService.DtoBase> AddAuxiliarAsync(LabManagerCliente.AdministradorAuxiliarService.View_Auxiliar newAuxiliar) {
            return base.Channel.AddAuxiliarAsync(newAuxiliar);
        }
        
        public LabManagerCliente.AdministradorAuxiliarService.DtoBase EditAuxiliar(LabManagerCliente.AdministradorAuxiliarService.View_Auxiliar editAuxiliar1) {
            return base.Channel.EditAuxiliar(editAuxiliar1);
        }
        
        public System.Threading.Tasks.Task<LabManagerCliente.AdministradorAuxiliarService.DtoBase> EditAuxiliarAsync(LabManagerCliente.AdministradorAuxiliarService.View_Auxiliar editAuxiliar) {
            return base.Channel.EditAuxiliarAsync(editAuxiliar);
        }
    }
}
