//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LabManagerCliente.MantenimientoService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DtoBase", Namespace="http://schemas.datacontract.org/2004/07/Dtos")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(LabManagerCliente.MantenimientoService.InformacionEliminarEstudiantesInactivos))]
    public partial class DtoBase : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool ErrorField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MensajeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private byte[] TokenField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Error {
            get {
                return this.ErrorField;
            }
            set {
                if ((this.ErrorField.Equals(value) != true)) {
                    this.ErrorField = value;
                    this.RaisePropertyChanged("Error");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Mensaje {
            get {
                return this.MensajeField;
            }
            set {
                if ((object.ReferenceEquals(this.MensajeField, value) != true)) {
                    this.MensajeField = value;
                    this.RaisePropertyChanged("Mensaje");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public byte[] Token {
            get {
                return this.TokenField;
            }
            set {
                if ((object.ReferenceEquals(this.TokenField, value) != true)) {
                    this.TokenField = value;
                    this.RaisePropertyChanged("Token");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="InformacionEliminarEstudiantesInactivos", Namespace="http://schemas.datacontract.org/2004/07/Dtos.Gestion")]
    [System.SerializableAttribute()]
    public partial class InformacionEliminarEstudiantesInactivos : LabManagerCliente.MantenimientoService.DtoBase {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int EstudiantesCandidatosEliminarField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int EstudiantesInactivosField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int RegistrosHistorialEliminarField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int EstudiantesCandidatosEliminar {
            get {
                return this.EstudiantesCandidatosEliminarField;
            }
            set {
                if ((this.EstudiantesCandidatosEliminarField.Equals(value) != true)) {
                    this.EstudiantesCandidatosEliminarField = value;
                    this.RaisePropertyChanged("EstudiantesCandidatosEliminar");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int EstudiantesInactivos {
            get {
                return this.EstudiantesInactivosField;
            }
            set {
                if ((this.EstudiantesInactivosField.Equals(value) != true)) {
                    this.EstudiantesInactivosField = value;
                    this.RaisePropertyChanged("EstudiantesInactivos");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int RegistrosHistorialEliminar {
            get {
                return this.RegistrosHistorialEliminarField;
            }
            set {
                if ((this.RegistrosHistorialEliminarField.Equals(value) != true)) {
                    this.RegistrosHistorialEliminarField = value;
                    this.RaisePropertyChanged("RegistrosHistorialEliminar");
                }
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="MantenimientoService.IMantenimiento")]
    public interface IMantenimiento {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMantenimiento/getInformacioneliminarEstudiantes", ReplyAction="http://tempuri.org/IMantenimiento/getInformacioneliminarEstudiantesResponse")]
        LabManagerCliente.MantenimientoService.InformacionEliminarEstudiantesInactivos getInformacioneliminarEstudiantes(long UsuarioId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMantenimiento/getInformacioneliminarEstudiantes", ReplyAction="http://tempuri.org/IMantenimiento/getInformacioneliminarEstudiantesResponse")]
        System.Threading.Tasks.Task<LabManagerCliente.MantenimientoService.InformacionEliminarEstudiantesInactivos> getInformacioneliminarEstudiantesAsync(long UsuarioId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMantenimiento/EliminarEstudiantesInactivos", ReplyAction="http://tempuri.org/IMantenimiento/EliminarEstudiantesInactivosResponse")]
        LabManagerCliente.MantenimientoService.DtoBase EliminarEstudiantesInactivos(long UsuarioId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMantenimiento/EliminarEstudiantesInactivos", ReplyAction="http://tempuri.org/IMantenimiento/EliminarEstudiantesInactivosResponse")]
        System.Threading.Tasks.Task<LabManagerCliente.MantenimientoService.DtoBase> EliminarEstudiantesInactivosAsync(long UsuarioId);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IMantenimientoChannel : LabManagerCliente.MantenimientoService.IMantenimiento, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class MantenimientoClient : System.ServiceModel.ClientBase<LabManagerCliente.MantenimientoService.IMantenimiento>, LabManagerCliente.MantenimientoService.IMantenimiento {
        
        public MantenimientoClient() {
        }
        
        public MantenimientoClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public MantenimientoClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public MantenimientoClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public MantenimientoClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public LabManagerCliente.MantenimientoService.InformacionEliminarEstudiantesInactivos getInformacioneliminarEstudiantes(long UsuarioId) {
            return base.Channel.getInformacioneliminarEstudiantes(UsuarioId);
        }
        
        public System.Threading.Tasks.Task<LabManagerCliente.MantenimientoService.InformacionEliminarEstudiantesInactivos> getInformacioneliminarEstudiantesAsync(long UsuarioId) {
            return base.Channel.getInformacioneliminarEstudiantesAsync(UsuarioId);
        }
        
        public LabManagerCliente.MantenimientoService.DtoBase EliminarEstudiantesInactivos(long UsuarioId) {
            return base.Channel.EliminarEstudiantesInactivos(UsuarioId);
        }
        
        public System.Threading.Tasks.Task<LabManagerCliente.MantenimientoService.DtoBase> EliminarEstudiantesInactivosAsync(long UsuarioId) {
            return base.Channel.EliminarEstudiantesInactivosAsync(UsuarioId);
        }
    }
}
