//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LabManagerCliente.AdministradorSedeService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DtoBase", Namespace="http://schemas.datacontract.org/2004/07/Dtos")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(LabManagerCliente.AdministradorSedeService.View_Sede))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(LabManagerCliente.AdministradorSedeService.Lista_View_Sede))]
    public partial class DtoBase : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool ErrorField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MensajeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private byte[] TokenField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Error {
            get {
                return this.ErrorField;
            }
            set {
                if ((this.ErrorField.Equals(value) != true)) {
                    this.ErrorField = value;
                    this.RaisePropertyChanged("Error");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Mensaje {
            get {
                return this.MensajeField;
            }
            set {
                if ((object.ReferenceEquals(this.MensajeField, value) != true)) {
                    this.MensajeField = value;
                    this.RaisePropertyChanged("Mensaje");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public byte[] Token {
            get {
                return this.TokenField;
            }
            set {
                if ((object.ReferenceEquals(this.TokenField, value) != true)) {
                    this.TokenField = value;
                    this.RaisePropertyChanged("Token");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="View_Sede", Namespace="http://schemas.datacontract.org/2004/07/Dtos.Basico")]
    [System.SerializableAttribute()]
    public partial class View_Sede : LabManagerCliente.AdministradorSedeService.DtoBase {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool ActivoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CreadoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long CreadoIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime FechaCreacionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> FechaModificacionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ModificadoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<long> ModificadoIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NombreField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int SedeIdField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Activo {
            get {
                return this.ActivoField;
            }
            set {
                if ((this.ActivoField.Equals(value) != true)) {
                    this.ActivoField = value;
                    this.RaisePropertyChanged("Activo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Creado {
            get {
                return this.CreadoField;
            }
            set {
                if ((object.ReferenceEquals(this.CreadoField, value) != true)) {
                    this.CreadoField = value;
                    this.RaisePropertyChanged("Creado");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long CreadoId {
            get {
                return this.CreadoIdField;
            }
            set {
                if ((this.CreadoIdField.Equals(value) != true)) {
                    this.CreadoIdField = value;
                    this.RaisePropertyChanged("CreadoId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime FechaCreacion {
            get {
                return this.FechaCreacionField;
            }
            set {
                if ((this.FechaCreacionField.Equals(value) != true)) {
                    this.FechaCreacionField = value;
                    this.RaisePropertyChanged("FechaCreacion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> FechaModificacion {
            get {
                return this.FechaModificacionField;
            }
            set {
                if ((this.FechaModificacionField.Equals(value) != true)) {
                    this.FechaModificacionField = value;
                    this.RaisePropertyChanged("FechaModificacion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Modificado {
            get {
                return this.ModificadoField;
            }
            set {
                if ((object.ReferenceEquals(this.ModificadoField, value) != true)) {
                    this.ModificadoField = value;
                    this.RaisePropertyChanged("Modificado");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<long> ModificadoId {
            get {
                return this.ModificadoIdField;
            }
            set {
                if ((this.ModificadoIdField.Equals(value) != true)) {
                    this.ModificadoIdField = value;
                    this.RaisePropertyChanged("ModificadoId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Nombre {
            get {
                return this.NombreField;
            }
            set {
                if ((object.ReferenceEquals(this.NombreField, value) != true)) {
                    this.NombreField = value;
                    this.RaisePropertyChanged("Nombre");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int SedeId {
            get {
                return this.SedeIdField;
            }
            set {
                if ((this.SedeIdField.Equals(value) != true)) {
                    this.SedeIdField = value;
                    this.RaisePropertyChanged("SedeId");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Lista_View_Sede", Namespace="http://schemas.datacontract.org/2004/07/Dtos.Basico")]
    [System.SerializableAttribute()]
    public partial class Lista_View_Sede : LabManagerCliente.AdministradorSedeService.DtoBase {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private LabManagerCliente.AdministradorSedeService.View_Sede[] ItemsField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public LabManagerCliente.AdministradorSedeService.View_Sede[] Items {
            get {
                return this.ItemsField;
            }
            set {
                if ((object.ReferenceEquals(this.ItemsField, value) != true)) {
                    this.ItemsField = value;
                    this.RaisePropertyChanged("Items");
                }
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="AdministradorSedeService.IAdministradorSede")]
    public interface IAdministradorSede {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAdministradorSede/getSede", ReplyAction="http://tempuri.org/IAdministradorSede/getSedeResponse")]
        LabManagerCliente.AdministradorSedeService.Lista_View_Sede getSede(string FiltroTexto, System.Nullable<bool> Activo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAdministradorSede/getSede", ReplyAction="http://tempuri.org/IAdministradorSede/getSedeResponse")]
        System.Threading.Tasks.Task<LabManagerCliente.AdministradorSedeService.Lista_View_Sede> getSedeAsync(string FiltroTexto, System.Nullable<bool> Activo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAdministradorSede/AddSede", ReplyAction="http://tempuri.org/IAdministradorSede/AddSedeResponse")]
        LabManagerCliente.AdministradorSedeService.DtoBase AddSede(LabManagerCliente.AdministradorSedeService.View_Sede newSede);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAdministradorSede/AddSede", ReplyAction="http://tempuri.org/IAdministradorSede/AddSedeResponse")]
        System.Threading.Tasks.Task<LabManagerCliente.AdministradorSedeService.DtoBase> AddSedeAsync(LabManagerCliente.AdministradorSedeService.View_Sede newSede);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAdministradorSede/EditSede", ReplyAction="http://tempuri.org/IAdministradorSede/EditSedeResponse")]
        LabManagerCliente.AdministradorSedeService.DtoBase EditSede([System.ServiceModel.MessageParameterAttribute(Name="editSede")] LabManagerCliente.AdministradorSedeService.View_Sede editSede1);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAdministradorSede/EditSede", ReplyAction="http://tempuri.org/IAdministradorSede/EditSedeResponse")]
        System.Threading.Tasks.Task<LabManagerCliente.AdministradorSedeService.DtoBase> EditSedeAsync(LabManagerCliente.AdministradorSedeService.View_Sede editSede);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IAdministradorSedeChannel : LabManagerCliente.AdministradorSedeService.IAdministradorSede, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class AdministradorSedeClient : System.ServiceModel.ClientBase<LabManagerCliente.AdministradorSedeService.IAdministradorSede>, LabManagerCliente.AdministradorSedeService.IAdministradorSede {
        
        public AdministradorSedeClient() {
        }
        
        public AdministradorSedeClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public AdministradorSedeClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AdministradorSedeClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AdministradorSedeClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public LabManagerCliente.AdministradorSedeService.Lista_View_Sede getSede(string FiltroTexto, System.Nullable<bool> Activo) {
            return base.Channel.getSede(FiltroTexto, Activo);
        }
        
        public System.Threading.Tasks.Task<LabManagerCliente.AdministradorSedeService.Lista_View_Sede> getSedeAsync(string FiltroTexto, System.Nullable<bool> Activo) {
            return base.Channel.getSedeAsync(FiltroTexto, Activo);
        }
        
        public LabManagerCliente.AdministradorSedeService.DtoBase AddSede(LabManagerCliente.AdministradorSedeService.View_Sede newSede) {
            return base.Channel.AddSede(newSede);
        }
        
        public System.Threading.Tasks.Task<LabManagerCliente.AdministradorSedeService.DtoBase> AddSedeAsync(LabManagerCliente.AdministradorSedeService.View_Sede newSede) {
            return base.Channel.AddSedeAsync(newSede);
        }
        
        public LabManagerCliente.AdministradorSedeService.DtoBase EditSede(LabManagerCliente.AdministradorSedeService.View_Sede editSede1) {
            return base.Channel.EditSede(editSede1);
        }
        
        public System.Threading.Tasks.Task<LabManagerCliente.AdministradorSedeService.DtoBase> EditSedeAsync(LabManagerCliente.AdministradorSedeService.View_Sede editSede) {
            return base.Channel.EditSedeAsync(editSede);
        }
    }
}
