//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LabManagerCliente.EstadoMultasService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DtoBase", Namespace="http://schemas.datacontract.org/2004/07/Dtos")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(LabManagerCliente.EstadoMultasService.View_EstadoMultas))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(LabManagerCliente.EstadoMultasService.Lista_View_EstadoMultas))]
    public partial class DtoBase : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool ErrorField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MensajeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private byte[] TokenField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Error {
            get {
                return this.ErrorField;
            }
            set {
                if ((this.ErrorField.Equals(value) != true)) {
                    this.ErrorField = value;
                    this.RaisePropertyChanged("Error");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Mensaje {
            get {
                return this.MensajeField;
            }
            set {
                if ((object.ReferenceEquals(this.MensajeField, value) != true)) {
                    this.MensajeField = value;
                    this.RaisePropertyChanged("Mensaje");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public byte[] Token {
            get {
                return this.TokenField;
            }
            set {
                if ((object.ReferenceEquals(this.TokenField, value) != true)) {
                    this.TokenField = value;
                    this.RaisePropertyChanged("Token");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="View_EstadoMultas", Namespace="http://schemas.datacontract.org/2004/07/Dtos.Reportes")]
    [System.SerializableAttribute()]
    public partial class View_EstadoMultas : LabManagerCliente.EstadoMultasService.DtoBase {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescripcionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DeudorField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DeudorDocumentoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long DeudorIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EstadoMultaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int EstadoMultaIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime FechaCreaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> FechaModificaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long MultaIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TipoDeudorField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UsuarioCreaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long UsuarioCreaIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UsuarioModificaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<long> UsuarioModificaIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ValorField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Descripcion {
            get {
                return this.DescripcionField;
            }
            set {
                if ((object.ReferenceEquals(this.DescripcionField, value) != true)) {
                    this.DescripcionField = value;
                    this.RaisePropertyChanged("Descripcion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Deudor {
            get {
                return this.DeudorField;
            }
            set {
                if ((object.ReferenceEquals(this.DeudorField, value) != true)) {
                    this.DeudorField = value;
                    this.RaisePropertyChanged("Deudor");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DeudorDocumento {
            get {
                return this.DeudorDocumentoField;
            }
            set {
                if ((object.ReferenceEquals(this.DeudorDocumentoField, value) != true)) {
                    this.DeudorDocumentoField = value;
                    this.RaisePropertyChanged("DeudorDocumento");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long DeudorId {
            get {
                return this.DeudorIdField;
            }
            set {
                if ((this.DeudorIdField.Equals(value) != true)) {
                    this.DeudorIdField = value;
                    this.RaisePropertyChanged("DeudorId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string EstadoMulta {
            get {
                return this.EstadoMultaField;
            }
            set {
                if ((object.ReferenceEquals(this.EstadoMultaField, value) != true)) {
                    this.EstadoMultaField = value;
                    this.RaisePropertyChanged("EstadoMulta");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int EstadoMultaId {
            get {
                return this.EstadoMultaIdField;
            }
            set {
                if ((this.EstadoMultaIdField.Equals(value) != true)) {
                    this.EstadoMultaIdField = value;
                    this.RaisePropertyChanged("EstadoMultaId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime FechaCrea {
            get {
                return this.FechaCreaField;
            }
            set {
                if ((this.FechaCreaField.Equals(value) != true)) {
                    this.FechaCreaField = value;
                    this.RaisePropertyChanged("FechaCrea");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> FechaModifica {
            get {
                return this.FechaModificaField;
            }
            set {
                if ((this.FechaModificaField.Equals(value) != true)) {
                    this.FechaModificaField = value;
                    this.RaisePropertyChanged("FechaModifica");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long MultaId {
            get {
                return this.MultaIdField;
            }
            set {
                if ((this.MultaIdField.Equals(value) != true)) {
                    this.MultaIdField = value;
                    this.RaisePropertyChanged("MultaId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TipoDeudor {
            get {
                return this.TipoDeudorField;
            }
            set {
                if ((object.ReferenceEquals(this.TipoDeudorField, value) != true)) {
                    this.TipoDeudorField = value;
                    this.RaisePropertyChanged("TipoDeudor");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string UsuarioCrea {
            get {
                return this.UsuarioCreaField;
            }
            set {
                if ((object.ReferenceEquals(this.UsuarioCreaField, value) != true)) {
                    this.UsuarioCreaField = value;
                    this.RaisePropertyChanged("UsuarioCrea");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long UsuarioCreaId {
            get {
                return this.UsuarioCreaIdField;
            }
            set {
                if ((this.UsuarioCreaIdField.Equals(value) != true)) {
                    this.UsuarioCreaIdField = value;
                    this.RaisePropertyChanged("UsuarioCreaId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string UsuarioModifica {
            get {
                return this.UsuarioModificaField;
            }
            set {
                if ((object.ReferenceEquals(this.UsuarioModificaField, value) != true)) {
                    this.UsuarioModificaField = value;
                    this.RaisePropertyChanged("UsuarioModifica");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<long> UsuarioModificaId {
            get {
                return this.UsuarioModificaIdField;
            }
            set {
                if ((this.UsuarioModificaIdField.Equals(value) != true)) {
                    this.UsuarioModificaIdField = value;
                    this.RaisePropertyChanged("UsuarioModificaId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Valor {
            get {
                return this.ValorField;
            }
            set {
                if ((this.ValorField.Equals(value) != true)) {
                    this.ValorField = value;
                    this.RaisePropertyChanged("Valor");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Lista_View_EstadoMultas", Namespace="http://schemas.datacontract.org/2004/07/Dtos.Reportes")]
    [System.SerializableAttribute()]
    public partial class Lista_View_EstadoMultas : LabManagerCliente.EstadoMultasService.DtoBase {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private LabManagerCliente.EstadoMultasService.View_EstadoMultas[] ItemsField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public LabManagerCliente.EstadoMultasService.View_EstadoMultas[] Items {
            get {
                return this.ItemsField;
            }
            set {
                if ((object.ReferenceEquals(this.ItemsField, value) != true)) {
                    this.ItemsField = value;
                    this.RaisePropertyChanged("Items");
                }
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="EstadoMultasService.IEstadoMultas")]
    public interface IEstadoMultas {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEstadoMultas/getEstadoMultas", ReplyAction="http://tempuri.org/IEstadoMultas/getEstadoMultasResponse")]
        LabManagerCliente.EstadoMultasService.Lista_View_EstadoMultas getEstadoMultas(System.Nullable<System.DateTime> FechaInicial, System.Nullable<System.DateTime> FechaFinal);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEstadoMultas/getEstadoMultas", ReplyAction="http://tempuri.org/IEstadoMultas/getEstadoMultasResponse")]
        System.Threading.Tasks.Task<LabManagerCliente.EstadoMultasService.Lista_View_EstadoMultas> getEstadoMultasAsync(System.Nullable<System.DateTime> FechaInicial, System.Nullable<System.DateTime> FechaFinal);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IEstadoMultasChannel : LabManagerCliente.EstadoMultasService.IEstadoMultas, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class EstadoMultasClient : System.ServiceModel.ClientBase<LabManagerCliente.EstadoMultasService.IEstadoMultas>, LabManagerCliente.EstadoMultasService.IEstadoMultas {
        
        public EstadoMultasClient() {
        }
        
        public EstadoMultasClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public EstadoMultasClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public EstadoMultasClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public EstadoMultasClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public LabManagerCliente.EstadoMultasService.Lista_View_EstadoMultas getEstadoMultas(System.Nullable<System.DateTime> FechaInicial, System.Nullable<System.DateTime> FechaFinal) {
            return base.Channel.getEstadoMultas(FechaInicial, FechaFinal);
        }
        
        public System.Threading.Tasks.Task<LabManagerCliente.EstadoMultasService.Lista_View_EstadoMultas> getEstadoMultasAsync(System.Nullable<System.DateTime> FechaInicial, System.Nullable<System.DateTime> FechaFinal) {
            return base.Channel.getEstadoMultasAsync(FechaInicial, FechaFinal);
        }
    }
}
