//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LabManagerCliente.VisorEquiposService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DtoBase", Namespace="http://schemas.datacontract.org/2004/07/Dtos")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(LabManagerCliente.VisorEquiposService.View_Equipo))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(LabManagerCliente.VisorEquiposService.Lista_View_Equipo))]
    public partial class DtoBase : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool ErrorField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MensajeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private byte[] TokenField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Error {
            get {
                return this.ErrorField;
            }
            set {
                if ((this.ErrorField.Equals(value) != true)) {
                    this.ErrorField = value;
                    this.RaisePropertyChanged("Error");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Mensaje {
            get {
                return this.MensajeField;
            }
            set {
                if ((object.ReferenceEquals(this.MensajeField, value) != true)) {
                    this.MensajeField = value;
                    this.RaisePropertyChanged("Mensaje");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public byte[] Token {
            get {
                return this.TokenField;
            }
            set {
                if ((object.ReferenceEquals(this.TokenField, value) != true)) {
                    this.TokenField = value;
                    this.RaisePropertyChanged("Token");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="View_Equipo", Namespace="http://schemas.datacontract.org/2004/07/Dtos.Basico")]
    [System.SerializableAttribute()]
    public partial class View_Equipo : LabManagerCliente.VisorEquiposService.DtoBase {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<bool> ActivoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CodigoInventarioField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CodigoLaboratorioField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CreadoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long CreadoIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long EquipoIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> FechaCompraField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime FechaCreadoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> FechaModificadoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MarcaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ModificadoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<long> ModificadoIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ReferenciaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SerialField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TipoEquipoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int TipoEquipoIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UsuarioInventarioResponsableField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UsuarioInventarioResponsableCodigoBarrasField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<long> UsuarioInventarioResponsableIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UsuarioResponsableField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UsuarioResponsableCodigoBarrasField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<long> UsuarioResponsableIdField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<bool> Activo {
            get {
                return this.ActivoField;
            }
            set {
                if ((this.ActivoField.Equals(value) != true)) {
                    this.ActivoField = value;
                    this.RaisePropertyChanged("Activo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CodigoInventario {
            get {
                return this.CodigoInventarioField;
            }
            set {
                if ((object.ReferenceEquals(this.CodigoInventarioField, value) != true)) {
                    this.CodigoInventarioField = value;
                    this.RaisePropertyChanged("CodigoInventario");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CodigoLaboratorio {
            get {
                return this.CodigoLaboratorioField;
            }
            set {
                if ((object.ReferenceEquals(this.CodigoLaboratorioField, value) != true)) {
                    this.CodigoLaboratorioField = value;
                    this.RaisePropertyChanged("CodigoLaboratorio");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Creado {
            get {
                return this.CreadoField;
            }
            set {
                if ((object.ReferenceEquals(this.CreadoField, value) != true)) {
                    this.CreadoField = value;
                    this.RaisePropertyChanged("Creado");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long CreadoId {
            get {
                return this.CreadoIdField;
            }
            set {
                if ((this.CreadoIdField.Equals(value) != true)) {
                    this.CreadoIdField = value;
                    this.RaisePropertyChanged("CreadoId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long EquipoId {
            get {
                return this.EquipoIdField;
            }
            set {
                if ((this.EquipoIdField.Equals(value) != true)) {
                    this.EquipoIdField = value;
                    this.RaisePropertyChanged("EquipoId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> FechaCompra {
            get {
                return this.FechaCompraField;
            }
            set {
                if ((this.FechaCompraField.Equals(value) != true)) {
                    this.FechaCompraField = value;
                    this.RaisePropertyChanged("FechaCompra");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime FechaCreado {
            get {
                return this.FechaCreadoField;
            }
            set {
                if ((this.FechaCreadoField.Equals(value) != true)) {
                    this.FechaCreadoField = value;
                    this.RaisePropertyChanged("FechaCreado");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> FechaModificado {
            get {
                return this.FechaModificadoField;
            }
            set {
                if ((this.FechaModificadoField.Equals(value) != true)) {
                    this.FechaModificadoField = value;
                    this.RaisePropertyChanged("FechaModificado");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Marca {
            get {
                return this.MarcaField;
            }
            set {
                if ((object.ReferenceEquals(this.MarcaField, value) != true)) {
                    this.MarcaField = value;
                    this.RaisePropertyChanged("Marca");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Modificado {
            get {
                return this.ModificadoField;
            }
            set {
                if ((object.ReferenceEquals(this.ModificadoField, value) != true)) {
                    this.ModificadoField = value;
                    this.RaisePropertyChanged("Modificado");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<long> ModificadoId {
            get {
                return this.ModificadoIdField;
            }
            set {
                if ((this.ModificadoIdField.Equals(value) != true)) {
                    this.ModificadoIdField = value;
                    this.RaisePropertyChanged("ModificadoId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Referencia {
            get {
                return this.ReferenciaField;
            }
            set {
                if ((object.ReferenceEquals(this.ReferenciaField, value) != true)) {
                    this.ReferenciaField = value;
                    this.RaisePropertyChanged("Referencia");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Serial {
            get {
                return this.SerialField;
            }
            set {
                if ((object.ReferenceEquals(this.SerialField, value) != true)) {
                    this.SerialField = value;
                    this.RaisePropertyChanged("Serial");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TipoEquipo {
            get {
                return this.TipoEquipoField;
            }
            set {
                if ((object.ReferenceEquals(this.TipoEquipoField, value) != true)) {
                    this.TipoEquipoField = value;
                    this.RaisePropertyChanged("TipoEquipo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int TipoEquipoId {
            get {
                return this.TipoEquipoIdField;
            }
            set {
                if ((this.TipoEquipoIdField.Equals(value) != true)) {
                    this.TipoEquipoIdField = value;
                    this.RaisePropertyChanged("TipoEquipoId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string UsuarioInventarioResponsable {
            get {
                return this.UsuarioInventarioResponsableField;
            }
            set {
                if ((object.ReferenceEquals(this.UsuarioInventarioResponsableField, value) != true)) {
                    this.UsuarioInventarioResponsableField = value;
                    this.RaisePropertyChanged("UsuarioInventarioResponsable");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string UsuarioInventarioResponsableCodigoBarras {
            get {
                return this.UsuarioInventarioResponsableCodigoBarrasField;
            }
            set {
                if ((object.ReferenceEquals(this.UsuarioInventarioResponsableCodigoBarrasField, value) != true)) {
                    this.UsuarioInventarioResponsableCodigoBarrasField = value;
                    this.RaisePropertyChanged("UsuarioInventarioResponsableCodigoBarras");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<long> UsuarioInventarioResponsableId {
            get {
                return this.UsuarioInventarioResponsableIdField;
            }
            set {
                if ((this.UsuarioInventarioResponsableIdField.Equals(value) != true)) {
                    this.UsuarioInventarioResponsableIdField = value;
                    this.RaisePropertyChanged("UsuarioInventarioResponsableId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string UsuarioResponsable {
            get {
                return this.UsuarioResponsableField;
            }
            set {
                if ((object.ReferenceEquals(this.UsuarioResponsableField, value) != true)) {
                    this.UsuarioResponsableField = value;
                    this.RaisePropertyChanged("UsuarioResponsable");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string UsuarioResponsableCodigoBarras {
            get {
                return this.UsuarioResponsableCodigoBarrasField;
            }
            set {
                if ((object.ReferenceEquals(this.UsuarioResponsableCodigoBarrasField, value) != true)) {
                    this.UsuarioResponsableCodigoBarrasField = value;
                    this.RaisePropertyChanged("UsuarioResponsableCodigoBarras");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<long> UsuarioResponsableId {
            get {
                return this.UsuarioResponsableIdField;
            }
            set {
                if ((this.UsuarioResponsableIdField.Equals(value) != true)) {
                    this.UsuarioResponsableIdField = value;
                    this.RaisePropertyChanged("UsuarioResponsableId");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Lista_View_Equipo", Namespace="http://schemas.datacontract.org/2004/07/Dtos.Basico")]
    [System.SerializableAttribute()]
    public partial class Lista_View_Equipo : LabManagerCliente.VisorEquiposService.DtoBase {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private LabManagerCliente.VisorEquiposService.View_Equipo[] ItemsField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public LabManagerCliente.VisorEquiposService.View_Equipo[] Items {
            get {
                return this.ItemsField;
            }
            set {
                if ((object.ReferenceEquals(this.ItemsField, value) != true)) {
                    this.ItemsField = value;
                    this.RaisePropertyChanged("Items");
                }
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="VisorEquiposService.IVisorEquipos")]
    public interface IVisorEquipos {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IVisorEquipos/getEquiposPrestados", ReplyAction="http://tempuri.org/IVisorEquipos/getEquiposPrestadosResponse")]
        LabManagerCliente.VisorEquiposService.Lista_View_Equipo getEquiposPrestados();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IVisorEquipos/getEquiposPrestados", ReplyAction="http://tempuri.org/IVisorEquipos/getEquiposPrestadosResponse")]
        System.Threading.Tasks.Task<LabManagerCliente.VisorEquiposService.Lista_View_Equipo> getEquiposPrestadosAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IVisorEquiposChannel : LabManagerCliente.VisorEquiposService.IVisorEquipos, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class VisorEquiposClient : System.ServiceModel.ClientBase<LabManagerCliente.VisorEquiposService.IVisorEquipos>, LabManagerCliente.VisorEquiposService.IVisorEquipos {
        
        public VisorEquiposClient() {
        }
        
        public VisorEquiposClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public VisorEquiposClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public VisorEquiposClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public VisorEquiposClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public LabManagerCliente.VisorEquiposService.Lista_View_Equipo getEquiposPrestados() {
            return base.Channel.getEquiposPrestados();
        }
        
        public System.Threading.Tasks.Task<LabManagerCliente.VisorEquiposService.Lista_View_Equipo> getEquiposPrestadosAsync() {
            return base.Channel.getEquiposPrestadosAsync();
        }
    }
}
