//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LabManagerCliente.AdministradorMultaService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DtoBase", Namespace="http://schemas.datacontract.org/2004/07/Dtos")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(LabManagerCliente.AdministradorMultaService.View_Multas))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(LabManagerCliente.AdministradorMultaService.Lista_View_EstadoMulta))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(LabManagerCliente.AdministradorMultaService.EstadoMulta))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(LabManagerCliente.AdministradorMultaService.Lista_View_Multas))]
    public partial class DtoBase : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool ErrorField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MensajeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private byte[] TokenField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Error {
            get {
                return this.ErrorField;
            }
            set {
                if ((this.ErrorField.Equals(value) != true)) {
                    this.ErrorField = value;
                    this.RaisePropertyChanged("Error");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Mensaje {
            get {
                return this.MensajeField;
            }
            set {
                if ((object.ReferenceEquals(this.MensajeField, value) != true)) {
                    this.MensajeField = value;
                    this.RaisePropertyChanged("Mensaje");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public byte[] Token {
            get {
                return this.TokenField;
            }
            set {
                if ((object.ReferenceEquals(this.TokenField, value) != true)) {
                    this.TokenField = value;
                    this.RaisePropertyChanged("Token");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="View_Multas", Namespace="http://schemas.datacontract.org/2004/07/Dtos.Basico")]
    [System.SerializableAttribute()]
    public partial class View_Multas : LabManagerCliente.AdministradorMultaService.DtoBase {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long CreadoIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescripcionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DeudorField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long DeudorIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EstadoMultaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int EstadoMultaIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime FechaCreacionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> FechaModificacionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<long> ModificadoIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long MultaIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NombreCreadorField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NombreModificaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ValorField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long CreadoId {
            get {
                return this.CreadoIdField;
            }
            set {
                if ((this.CreadoIdField.Equals(value) != true)) {
                    this.CreadoIdField = value;
                    this.RaisePropertyChanged("CreadoId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Descripcion {
            get {
                return this.DescripcionField;
            }
            set {
                if ((object.ReferenceEquals(this.DescripcionField, value) != true)) {
                    this.DescripcionField = value;
                    this.RaisePropertyChanged("Descripcion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Deudor {
            get {
                return this.DeudorField;
            }
            set {
                if ((object.ReferenceEquals(this.DeudorField, value) != true)) {
                    this.DeudorField = value;
                    this.RaisePropertyChanged("Deudor");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long DeudorId {
            get {
                return this.DeudorIdField;
            }
            set {
                if ((this.DeudorIdField.Equals(value) != true)) {
                    this.DeudorIdField = value;
                    this.RaisePropertyChanged("DeudorId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string EstadoMulta {
            get {
                return this.EstadoMultaField;
            }
            set {
                if ((object.ReferenceEquals(this.EstadoMultaField, value) != true)) {
                    this.EstadoMultaField = value;
                    this.RaisePropertyChanged("EstadoMulta");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int EstadoMultaId {
            get {
                return this.EstadoMultaIdField;
            }
            set {
                if ((this.EstadoMultaIdField.Equals(value) != true)) {
                    this.EstadoMultaIdField = value;
                    this.RaisePropertyChanged("EstadoMultaId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime FechaCreacion {
            get {
                return this.FechaCreacionField;
            }
            set {
                if ((this.FechaCreacionField.Equals(value) != true)) {
                    this.FechaCreacionField = value;
                    this.RaisePropertyChanged("FechaCreacion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> FechaModificacion {
            get {
                return this.FechaModificacionField;
            }
            set {
                if ((this.FechaModificacionField.Equals(value) != true)) {
                    this.FechaModificacionField = value;
                    this.RaisePropertyChanged("FechaModificacion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<long> ModificadoId {
            get {
                return this.ModificadoIdField;
            }
            set {
                if ((this.ModificadoIdField.Equals(value) != true)) {
                    this.ModificadoIdField = value;
                    this.RaisePropertyChanged("ModificadoId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long MultaId {
            get {
                return this.MultaIdField;
            }
            set {
                if ((this.MultaIdField.Equals(value) != true)) {
                    this.MultaIdField = value;
                    this.RaisePropertyChanged("MultaId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NombreCreador {
            get {
                return this.NombreCreadorField;
            }
            set {
                if ((object.ReferenceEquals(this.NombreCreadorField, value) != true)) {
                    this.NombreCreadorField = value;
                    this.RaisePropertyChanged("NombreCreador");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NombreModifica {
            get {
                return this.NombreModificaField;
            }
            set {
                if ((object.ReferenceEquals(this.NombreModificaField, value) != true)) {
                    this.NombreModificaField = value;
                    this.RaisePropertyChanged("NombreModifica");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Valor {
            get {
                return this.ValorField;
            }
            set {
                if ((this.ValorField.Equals(value) != true)) {
                    this.ValorField = value;
                    this.RaisePropertyChanged("Valor");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Lista_View_EstadoMulta", Namespace="http://schemas.datacontract.org/2004/07/Dtos.Basico")]
    [System.SerializableAttribute()]
    public partial class Lista_View_EstadoMulta : LabManagerCliente.AdministradorMultaService.DtoBase {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private LabManagerCliente.AdministradorMultaService.EstadoMulta[] ItemsField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public LabManagerCliente.AdministradorMultaService.EstadoMulta[] Items {
            get {
                return this.ItemsField;
            }
            set {
                if ((object.ReferenceEquals(this.ItemsField, value) != true)) {
                    this.ItemsField = value;
                    this.RaisePropertyChanged("Items");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="EstadoMulta", Namespace="http://schemas.datacontract.org/2004/07/Dtos.Basico")]
    [System.SerializableAttribute()]
    public partial class EstadoMulta : LabManagerCliente.AdministradorMultaService.DtoBase {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescripcionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int EstadoMultaIdField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Descripcion {
            get {
                return this.DescripcionField;
            }
            set {
                if ((object.ReferenceEquals(this.DescripcionField, value) != true)) {
                    this.DescripcionField = value;
                    this.RaisePropertyChanged("Descripcion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int EstadoMultaId {
            get {
                return this.EstadoMultaIdField;
            }
            set {
                if ((this.EstadoMultaIdField.Equals(value) != true)) {
                    this.EstadoMultaIdField = value;
                    this.RaisePropertyChanged("EstadoMultaId");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Lista_View_Multas", Namespace="http://schemas.datacontract.org/2004/07/Dtos.Basico")]
    [System.SerializableAttribute()]
    public partial class Lista_View_Multas : LabManagerCliente.AdministradorMultaService.DtoBase {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private LabManagerCliente.AdministradorMultaService.View_Multas[] ItemsField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public LabManagerCliente.AdministradorMultaService.View_Multas[] Items {
            get {
                return this.ItemsField;
            }
            set {
                if ((object.ReferenceEquals(this.ItemsField, value) != true)) {
                    this.ItemsField = value;
                    this.RaisePropertyChanged("Items");
                }
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="AdministradorMultaService.IAdministradorMulta")]
    public interface IAdministradorMulta {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAdministradorMulta/getMultas", ReplyAction="http://tempuri.org/IAdministradorMulta/getMultasResponse")]
        LabManagerCliente.AdministradorMultaService.Lista_View_Multas getMultas(long UsuarioId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAdministradorMulta/getMultas", ReplyAction="http://tempuri.org/IAdministradorMulta/getMultasResponse")]
        System.Threading.Tasks.Task<LabManagerCliente.AdministradorMultaService.Lista_View_Multas> getMultasAsync(long UsuarioId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAdministradorMulta/AddMulta", ReplyAction="http://tempuri.org/IAdministradorMulta/AddMultaResponse")]
        LabManagerCliente.AdministradorMultaService.DtoBase AddMulta(LabManagerCliente.AdministradorMultaService.View_Multas newMulta);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAdministradorMulta/AddMulta", ReplyAction="http://tempuri.org/IAdministradorMulta/AddMultaResponse")]
        System.Threading.Tasks.Task<LabManagerCliente.AdministradorMultaService.DtoBase> AddMultaAsync(LabManagerCliente.AdministradorMultaService.View_Multas newMulta);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAdministradorMulta/EditMulta", ReplyAction="http://tempuri.org/IAdministradorMulta/EditMultaResponse")]
        LabManagerCliente.AdministradorMultaService.DtoBase EditMulta([System.ServiceModel.MessageParameterAttribute(Name="editMulta")] LabManagerCliente.AdministradorMultaService.View_Multas editMulta1);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAdministradorMulta/EditMulta", ReplyAction="http://tempuri.org/IAdministradorMulta/EditMultaResponse")]
        System.Threading.Tasks.Task<LabManagerCliente.AdministradorMultaService.DtoBase> EditMultaAsync(LabManagerCliente.AdministradorMultaService.View_Multas editMulta);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAdministradorMulta/getEstadosMulta", ReplyAction="http://tempuri.org/IAdministradorMulta/getEstadosMultaResponse")]
        LabManagerCliente.AdministradorMultaService.Lista_View_EstadoMulta getEstadosMulta();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAdministradorMulta/getEstadosMulta", ReplyAction="http://tempuri.org/IAdministradorMulta/getEstadosMultaResponse")]
        System.Threading.Tasks.Task<LabManagerCliente.AdministradorMultaService.Lista_View_EstadoMulta> getEstadosMultaAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IAdministradorMultaChannel : LabManagerCliente.AdministradorMultaService.IAdministradorMulta, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class AdministradorMultaClient : System.ServiceModel.ClientBase<LabManagerCliente.AdministradorMultaService.IAdministradorMulta>, LabManagerCliente.AdministradorMultaService.IAdministradorMulta {
        
        public AdministradorMultaClient() {
        }
        
        public AdministradorMultaClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public AdministradorMultaClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AdministradorMultaClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AdministradorMultaClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public LabManagerCliente.AdministradorMultaService.Lista_View_Multas getMultas(long UsuarioId) {
            return base.Channel.getMultas(UsuarioId);
        }
        
        public System.Threading.Tasks.Task<LabManagerCliente.AdministradorMultaService.Lista_View_Multas> getMultasAsync(long UsuarioId) {
            return base.Channel.getMultasAsync(UsuarioId);
        }
        
        public LabManagerCliente.AdministradorMultaService.DtoBase AddMulta(LabManagerCliente.AdministradorMultaService.View_Multas newMulta) {
            return base.Channel.AddMulta(newMulta);
        }
        
        public System.Threading.Tasks.Task<LabManagerCliente.AdministradorMultaService.DtoBase> AddMultaAsync(LabManagerCliente.AdministradorMultaService.View_Multas newMulta) {
            return base.Channel.AddMultaAsync(newMulta);
        }
        
        public LabManagerCliente.AdministradorMultaService.DtoBase EditMulta(LabManagerCliente.AdministradorMultaService.View_Multas editMulta1) {
            return base.Channel.EditMulta(editMulta1);
        }
        
        public System.Threading.Tasks.Task<LabManagerCliente.AdministradorMultaService.DtoBase> EditMultaAsync(LabManagerCliente.AdministradorMultaService.View_Multas editMulta) {
            return base.Channel.EditMultaAsync(editMulta);
        }
        
        public LabManagerCliente.AdministradorMultaService.Lista_View_EstadoMulta getEstadosMulta() {
            return base.Channel.getEstadosMulta();
        }
        
        public System.Threading.Tasks.Task<LabManagerCliente.AdministradorMultaService.Lista_View_EstadoMulta> getEstadosMultaAsync() {
            return base.Channel.getEstadosMultaAsync();
        }
    }
}
